#!/usr/bin/env python3
"""Emit the probe registration for every stream in a complete-Small manifest.

The property that made the archived core-only guider converge was that its
validation set and its delivery set were the same list: probes were generated
from CHISA's oracle selection, so a signal could not be "verified" while going
unproduced, or produced while going unverified.  This keeps that property on
the complete TestHarness without baking a snapshot count into the generator:
the manifest supplied on the command line is the authority and any future
change appears as a generated-registry diff.

Every stream is emitted, in manifest order, as one row of the constexpr
``kSystemProbeManifest`` table.  The registration code loops over that table;
expanding 2,000 copies of a registration macro made a one-line diagnostic
change consume several minutes and multiple gigabytes in Clang.

The consumer defines `SYSPROBE_STREAM`.  Streams with no model binding
register as UNMODELED, which the probe summary reports honestly rather than
silently passing.  Subsystems therefore light up incrementally without this
file being regenerated, and a stream that appears or disappears from the
manifest shows up as a registration diff instead of as silence.

Fails closed: a manifest whose entries lack a trace key, or that collides two
streams onto one key, is an error rather than a quietly shortened list.

Usage:
  generate_system_probes.py --manifest <oracle_manifest.json>
                            --output <system_probe_registry.inc>
                            [--metadata <system_probe_registry.json>]
"""

from __future__ import annotations

import argparse
import collections
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from scope_model_signals import subsystem_of  # noqa: E402


def c_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def relative_to_repo(path: str) -> str:
    """Header comments must not bake in a machine-specific absolute path."""
    repo_root = Path(__file__).resolve().parents[3]
    resolved = Path(path).resolve()
    try:
        return str(resolved.relative_to(repo_root))
    except ValueError:
        return str(path)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--manifest", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--metadata", type=Path)
    args = parser.parse_args()

    manifest = json.loads(args.manifest.read_text())
    oracles = manifest.get("oracles")
    if not oracles:
        print(f"ERROR: {args.manifest} contains no oracles", file=sys.stderr)
        return 2

    seen: dict[str, str] = {}
    rows = []
    for index, entry in enumerate(oracles):
        flat = entry.get("flat")
        key = entry.get("traceKey")
        if not flat or not key:
            print(f"ERROR: manifest entry {index} lacks flat/traceKey: {entry}",
                  file=sys.stderr)
            return 2
        if key in seen:
            print(f"ERROR: trace key {key!r} used by both {seen[key]!r} and "
                  f"{flat!r}; the registry would silently drop one",
                  file=sys.stderr)
            return 2
        seen[key] = flat
        kind = entry.get("kind")
        if kind not in ("reg", "comb"):
            print(f"ERROR: manifest entry {index} has invalid kind {kind!r}",
                  file=sys.stderr)
            return 2
        rows.append({
            "subsystem": subsystem_of(flat),
            "key": key,
            "flat": flat,
            "width": int(entry.get("width", 0)),
            "elemBytes": int(entry.get("elemBytes", 0)),
            "kind": kind,
        })

    by_subsystem = collections.Counter(row["subsystem"] for row in rows)

    lines = [
        "// Generated by duts/boom-repcut/scripts/generate_system_probes.py.",
        "// Do not edit. Regenerate when the oracle manifest changes; the diff",
        "// is the record of what CHISA now asks the model to produce.",
        "//",
        f"// manifest: {relative_to_repo(args.manifest)}",
        f"// streams:  {len(rows)}",
        "//",
        "// A stream with no model binding registers as UNMODELED and is",
        "// reported as such.",
        "",
        "#pragma once",
        "#include <cstddef>",
        "#include \"oracle_timing.h\"",
        "",
        "namespace chisa::boom_system {",
        "struct SystemProbeManifestRow {",
        "  const char* subsystem;",
        "  const char* key;",
        "  const char* flat;",
        "  unsigned width;",
        "  unsigned elem_bytes;",
        "  OracleKind kind;",
        "};",
        "inline constexpr SystemProbeManifestRow kSystemProbeManifest[] = {",
        "",
    ]
    for name, count in sorted(by_subsystem.items(), key=lambda kv: -kv[1]):
        lines.append(f"// {count:>5}  {name}")
    lines.append("")

    current = None
    for row in rows:
        if row["subsystem"] != current:
            current = row["subsystem"]
            lines.append(f"// ---- {current} ----")
        lines.append(
            "  {" + ", ".join((
                c_string(row["subsystem"]), c_string(row["key"]),
                c_string(row["flat"]), str(row["width"]),
                str(row["elemBytes"]),
                "OracleKind::Register" if row["kind"] == "reg"
                else "OracleKind::Combinational",
            )) + "},")
    lines.extend([
        "};",
        "inline constexpr std::size_t kSystemProbeManifestCount =",
        "    sizeof(kSystemProbeManifest) / sizeof(kSystemProbeManifest[0]);",
        "}  // namespace chisa::boom_system",
        "",
    ])

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines))
    print(f"wrote {args.output}: {len(rows)} streams across "
          f"{len(by_subsystem)} subsystems")
    for name, count in sorted(by_subsystem.items(), key=lambda kv: -kv[1]):
        print(f"  {count:>5}  {name}")

    if args.metadata:
        args.metadata.write_text(json.dumps({
            "manifest": str(args.manifest),
            "streamCount": len(rows),
            "bySubsystem": dict(by_subsystem),
            "streams": rows,
        }, indent=2))
        print(f"wrote {args.metadata}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
