#!/usr/bin/env python3
"""Generate the OracleRecord header: one cycle's image of every qualified
oracle stream, numbered in manifest order, at its natural element width.
The CLI requires an explicit storage layout: Small's grouped image or the
existing Large record's packed layout. Typed views check exact lane offsets
and field/word identity in addition to the historical writer layout hash.

The record is width-independent (it does not know W or the block layout);
the per-width writers carry the same layout hash and static_assert on it,
so a writer regenerated against a different contract cannot be linked with a
stale record.  Lane index == manifest index == kSystemProbeManifest row."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

from generate_system_oracle_writer import (
    layout_hash, qualified_streams, sha256)

CHUNK_BYTES = 64
PAD_LANE = 0xFFFF


def lane_identity_hash(entry: dict[str, Any]) -> int:
    # Unlike the historical writer layout hash, this also identifies the
    # original field and the word of a split-wide field. Keep the old hash
    # stable for the existing writer ABI and check both in typed views.
    identity = [entry["traceKey"], entry["flat"], entry["kind"],
                entry.get("word", 0), entry.get("words", 1)]
    digest = hashlib.sha256(json.dumps(identity, separators=(",", ":")).encode())
    return int.from_bytes(digest.digest()[:8], "big")


def record_layout(selected: list[dict[str, Any]], mode: str = "image") -> dict[str, Any]:
    # The record is the model's contract image (gen_image.py): the same
    # grouping, array folding and register/combinational sections, so the
    # model writes its fields in place and the record needs no sampling of
    # them.  Lane index is still the manifest index.
    from gen_image import compute_layout, validate_oracles
    validate_oracles(selected)
    if mode == "image":
        lane_offset, run = compute_layout(selected)
        offsets = [lane_offset[i] for i in range(len(selected))]
    elif mode == "packed":
        # The checked-in Large record predates model's grouped image. Its
        # unaligned offsets are an ABI, not permission to reinterpret_cast
        # an aligned Small/Large struct onto those bytes.
        offsets, run = [], 0
        for entry in selected:
            offsets.append(run)
            run += entry["elemBytes"]
    else:
        raise ValueError(f"unknown record layout: {mode}")
    chunks = (run + CHUNK_BYTES - 1) // CHUNK_BYTES
    padded = chunks * CHUNK_BYTES
    if padded > 0xffff:
        raise ValueError("record byte offsets exceed the uint16 ABI")
    byte_to_lane = [PAD_LANE] * padded
    for lane, entry in enumerate(selected):
        for byte in range(int(entry["elemBytes"])):
            if byte_to_lane[offsets[lane] + byte] != PAD_LANE:
                raise ValueError(f"record lanes overlap at byte {offsets[lane] + byte}")
            byte_to_lane[offsets[lane] + byte] = lane
    chunk_first = []
    chunk_last = []
    for chunk in range(chunks):
        lanes = [byte_to_lane[b] for b in range(chunk * CHUNK_BYTES,
                                                 (chunk + 1) * CHUNK_BYTES)
                 if byte_to_lane[b] != PAD_LANE]
        chunk_first.append(min(lanes) if lanes else PAD_LANE)
        chunk_last.append(max(lanes) if lanes else PAD_LANE)
    return {
        "offsets": offsets, "bytes": run, "chunks": chunks, "padded": padded,
        "byteToLane": byte_to_lane, "chunkFirstLane": chunk_first,
        "chunkLastLane": chunk_last, "hash": layout_hash(selected), "mode": mode,
    }


def render_header(selected: list[dict[str, Any]],
                  layout: dict[str, Any]) -> str:
    lanes = len(selected)
    lines = [
        "// AUTO-GENERATED by generate_system_oracle_record.py. DO NOT EDIT.",
        "// One cycle's image of every qualified oracle stream in manifest",
        "// order at natural element width.  Lane index == manifest index.",
        "#pragma once",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <cstring>",
        "#if defined(__AVX512BW__) && defined(__AVX512VL__) && defined(__BMI2__)",
        "#include <immintrin.h>",
        "#define CHISA_ORACLE_RECORD_MASKED_STORE 1",
        "#endif",
        "",
        "namespace chisa::boom_system {",
        f"inline constexpr std::size_t kOracleRecordLanes = {lanes}u;",
        f"inline constexpr std::size_t kOracleRecordBytes = {layout['bytes']}u;",
        f"inline constexpr std::size_t kOracleRecordChunkBytes = {CHUNK_BYTES}u;",
        f"inline constexpr std::size_t kOracleRecordChunks = {layout['chunks']}u;",
        f"inline constexpr std::size_t kOracleRecordPaddedBytes = {layout['padded']}u;",
        f"inline constexpr std::uint64_t kOracleRecordLayoutHash = "
        f"0x{layout['hash']:016x}ull;",
        f"inline constexpr std::uint16_t kOracleRecordPadLane = 0x{PAD_LANE:04x}u;",
        "",
        "inline constexpr std::array<std::uint64_t, 65> kOracleRecordWidthMask = [] {",
        "  std::array<std::uint64_t, 65> table{};",
        "  for (int w = 0; w < 64; ++w)",
        "    table[static_cast<std::size_t>(w)] = (std::uint64_t{1} << w) - 1u;",
        "  table[64] = ~std::uint64_t{0};",
        "  return table;",
        "}();",
        "",
        "struct OracleRecordLane {",
        "  std::uint16_t offset;  // byte offset inside the record",
        "  std::uint8_t bytes;    // element size: 1, 2, 4 or 8",
        "  std::uint8_t width;    // manifest bit width, <= 8 * bytes",
        "  std::uint8_t mask;     // (1 << bytes) - 1: byte-store mask",
        "};",
        "",
        "inline constexpr OracleRecordLane kOracleRecordLane[kOracleRecordLanes] = {",
    ]
    for lane, entry in enumerate(selected):
        eb = int(entry['elemBytes'])
        lines.append(
            f"  {{{layout['offsets'][lane]}u, {eb}u, "
            f"{int(entry['width'])}u, {(1 << eb) - 1}u}},")
    lines.append("};")
    lines.append("")
    lines.append("// Field identity includes flat name, kind, and wide-word index/count.")
    lines.append("// Compile-time view checks consume this table; it owns no model state.")
    lines.append("struct OracleRecordFieldIdentity {")
    lines.append("  std::uint64_t hash;")
    lines.append("  std::uint8_t kind;  // 0=register, 1=combinational")
    lines.append("  std::uint8_t word, words;")
    lines.append("};")
    lines.append("inline constexpr OracleRecordFieldIdentity kOracleRecordLaneIdentity[kOracleRecordLanes] = {")
    for first in range(0, lanes, 4):
        lines.append("  " + ", ".join(f"{{0x{lane_identity_hash(e):016x}ull, "
                                      f"{0 if e['kind'] == 'reg' else 1}, "
                                      f"{e.get('word', 0)}, {e.get('words', 1)}}}"
                                      for e in selected[first:first + 4]) + ",")
    lines.append("};")
    lines.append("")
    lines.append("// Byte offset -> lane, padding bytes map to kOracleRecordPadLane.")
    lines.append("inline constexpr std::uint16_t kOracleRecordByteLane"
                 "[kOracleRecordPaddedBytes] = {")
    row: list[str] = []
    for value in layout["byteToLane"]:
        row.append(f"{value}u")
        if len(row) == 16:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("  " + ", ".join(row) + ",")
    lines.append("};")
    lines.append("")
    lines.append("// First/last lane intersecting each 64-byte chunk "
                 "(pad-only chunks: kOracleRecordPadLane).")
    lines.append("inline constexpr std::uint16_t kOracleRecordChunkFirstLane"
                 "[kOracleRecordChunks] = {")
    lines.append("  " + ", ".join(f"{v}u" for v in layout["chunkFirstLane"]) + ",")
    lines.append("};")
    lines.append("inline constexpr std::uint16_t kOracleRecordChunkLastLane"
                 "[kOracleRecordChunks] = {")
    lines.append("  " + ", ".join(f"{v}u" for v in layout["chunkLastLane"]) + ",")
    lines.append("};")
    lines.extend([
        "",
        "/** The per-cycle oracle image.  Zero-initialized: the first cycle's",
        "  * image is the generated simulator's pre-edge zero image.  Pad bytes",
        "  * past kOracleRecordBytes are never written, so whole-record and",
        "  * whole-chunk comparisons are well defined. */",
        "struct alignas(kOracleRecordChunkBytes) OracleRecord {",
        "  unsigned char bytes[kOracleRecordPaddedBytes] = {};",
        "",
        "  /** Width-masked store of one lane; lanes >= kOracleRecordLanes",
        "    * (scratch) are dropped.  Branch-free where the ISA allows: the",
        "    * element size varies lane to lane in an unpredictable pattern, so",
        "    * a size switch mispredicts on a large fraction of the ~2,000 stores",
        "    * per cycle (measured: sampling 1,450 -> 2,536 ns/cycle). */",
        "  void store(std::size_t lane, std::uint64_t value) {",
        "    if (lane >= kOracleRecordLanes) return;",
        "    const OracleRecordLane& d = kOracleRecordLane[lane];",
        "#ifdef CHISA_ORACLE_RECORD_MASKED_STORE",
        "    const std::uint64_t masked = _bzhi_u64(value, d.width);",
        "    _mm_mask_storeu_epi8(bytes + d.offset, static_cast<__mmask16>(d.mask),",
        "                         _mm_cvtsi64_si128(static_cast<long long>(masked)));",
        "#else",
        "    value &= kOracleRecordWidthMask[d.width];",
        "    switch (d.bytes) {",
        "      case 1: bytes[d.offset] = static_cast<unsigned char>(value); break;",
        "      case 2: { const std::uint16_t s = static_cast<std::uint16_t>(value);",
        "        std::memcpy(bytes + d.offset, &s, 2); break; }",
        "      case 4: { const std::uint32_t s = static_cast<std::uint32_t>(value);",
        "        std::memcpy(bytes + d.offset, &s, 4); break; }",
        "      default: std::memcpy(bytes + d.offset, &value, 8); break;",
        "    }",
        "#endif",
        "  }",
        "  /** store() only when the (width-masked) value differs from what the",
        "    * record holds: ~95% of sampled values are unchanged each cycle, so",
        "    * the compare is a well-predicted branch that saves the store. The",
        "    * compare reads 8 bytes at the lane's offset (the record's tail",
        "    * padding keeps that in bounds) and masks to the lane's width. */",
        "  bool store_if_changed(std::size_t lane, std::uint64_t value) {",
        "    if (lane >= kOracleRecordLanes) return false;",
        "    const OracleRecordLane& d = kOracleRecordLane[lane];",
        "    std::uint64_t held;",
        "    std::memcpy(&held, bytes + d.offset, 8);",
        "    const std::uint64_t width_mask = kOracleRecordWidthMask[d.width];",
        "    if (((held ^ value) & width_mask) == 0) return false;",
        "    store(lane, value);",
        "    return true;",
        "  }",
        "  std::uint64_t load(std::size_t lane) const {",
        "    if (lane >= kOracleRecordLanes) return 0;",
        "    const OracleRecordLane& d = kOracleRecordLane[lane];",
        "    switch (d.bytes) {",
        "      case 1: return bytes[d.offset];",
        "      case 2: { std::uint16_t s; std::memcpy(&s, bytes + d.offset, 2); return s; }",
        "      case 4: { std::uint32_t s; std::memcpy(&s, bytes + d.offset, 4); return s; }",
        "      default: { std::uint64_t s; std::memcpy(&s, bytes + d.offset, 8); return s; }",
        "    }",
        "  }",
        "  const unsigned char* chunk(std::size_t c) const {",
        "    return bytes + c * kOracleRecordChunkBytes;",
        "  }",
        "  unsigned char* chunk(std::size_t c) {",
        "    return bytes + c * kOracleRecordChunkBytes;",
        "  }",
        "};",
        "",
        "}  // namespace chisa::boom_system",
        "",
    ])
    return "\n".join(lines)


def generate_record(manifest_path: Path, qualification_path: Path,
                    output_path: Path, metadata_path: Path | None,
                    mode: str = "image") -> int:
    manifest, qualification, selected = qualified_streams(
        manifest_path, qualification_path, 4)
    if len(selected) != len(manifest["oracles"]):
        raise ValueError(
            f"record needs the full manifest: {len(selected)} qualified of "
            f"{len(manifest['oracles'])}")
    if [o["traceKey"] for o in selected] != [o["traceKey"] for o in manifest["oracles"]]:
        raise ValueError("record lanes must follow the exact manifest order")
    for qualified, original in zip(selected, manifest["oracles"]):
        for name, default in (("word", 0), ("words", 1)):
            if name in qualified and (type(qualified[name]) is not int or
                                      qualified[name] != original.get(name, default)):
                raise ValueError(f"qualified stream {original['traceKey']} has {name} drift")
    # Older qualification schemas omit word/words. The full manifest has
    # already been joined by exact key/shape and content hash above; use its
    # authoritative word metadata instead of inventing default wide words.
    selected = manifest["oracles"]
    layout = record_layout(selected, mode)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_header(selected, layout), encoding="utf-8")
    if metadata_path is not None:
        metadata_path.parent.mkdir(parents=True, exist_ok=True)
        metadata_path.write_text(json.dumps({
            "schemaVersion": 1,
            "sourceManifest": {"path": str(manifest_path.resolve()),
                               "sha256": sha256(manifest_path)},
            "sourceQualification": {
                "path": str(qualification_path.resolve()),
                "sha256": sha256(qualification_path),
                "cycles": qualification["qualification"]["cycles"]},
            "lanes": len(selected), "bytes": layout["bytes"],
            "chunks": layout["chunks"], "paddedBytes": layout["padded"],
            "layoutHash": f"0x{layout['hash']:016x}", "recordLayout": mode,
        }, indent=2) + "\n", encoding="utf-8")
    return len(selected)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", required=True, type=Path)
    parser.add_argument("--qualification", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--metadata", type=Path)
    parser.add_argument("--layout", choices=("image", "packed"), required=True,
                        help="explicit storage ABI: Small=image, existing Large=packed")
    args = parser.parse_args()
    try:
        count = generate_record(args.manifest, args.qualification,
                                args.output, args.metadata, args.layout)
    except (OSError, ValueError, KeyError, json.JSONDecodeError) as error:
        print(f"SYSTEM_ORACLE_RECORD_FAIL: {error}")
        return 1
    print(f"SYSTEM_ORACLE_RECORD_OK lanes={count} output={args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
