#!/usr/bin/env python3
"""Generate the exact PeripheryBus sidecar-to-manifest oracle contract."""

from __future__ import annotations

import argparse
import re
import json
from pathlib import Path


PREFIX = "ldut.subsystem_cbus."

# These streams already occupy slots in the large active-face batch.  Keep
# those slots stable, but make their values come from the same exact sidecar
# snapshot as the other CBus streams.
LEGACY_KEYS = {
    "ldut_subsystem_cbus_atomics_d_first_counter",
    "ldut_subsystem_cbus_atomics_state_1",
    "ldut_subsystem_cbus_buffer_bundleIn_0_d_q_maybe_full",
    "ldut_subsystem_cbus_buffer_bundleIn_0_d_q_value",
    "ldut_subsystem_cbus_buffer_bundleIn_0_d_q_value_1",
    "ldut_subsystem_cbus_buffer_bundleOut_0_a_q_maybe_full",
    "ldut_subsystem_cbus_buffer_bundleOut_0_a_q_value",
    "ldut_subsystem_cbus_buffer_bundleOut_0_a_q_value_1",
    "ldut_subsystem_cbus_coupler_to_bootrom_fragmenter_dToggle",
    "ldut_subsystem_cbus_coupler_to_bootrom_fragmenter_gennum",
    "ldut_subsystem_cbus_coupler_to_bootrom_fragmenter_repeater_full",
    "ldut_subsystem_cbus_coupler_to_bootrom_fragmenter_repeater_saved_size",
    "ldut_subsystem_cbus_coupler_to_bootrom_fragmenter_repeater_saved_source",
    "ldut_subsystem_cbus_coupler_to_debug_fragmenter_dToggle",
    "ldut_subsystem_cbus_coupler_to_debug_fragmenter_gennum",
    "ldut_subsystem_cbus_coupler_to_debug_fragmenter_repeater_full",
    "ldut_subsystem_cbus_coupler_to_debug_fragmenter_repeater_saved_opcode",
    "ldut_subsystem_cbus_coupler_to_debug_fragmenter_repeater_saved_size",
    "ldut_subsystem_cbus_coupler_to_debug_fragmenter_repeater_saved_source",
    "ldut_subsystem_cbus_out_xbar_beatsLeft",
    "ldut_subsystem_cbus_out_xbar_readys_mask",
    "ldut_subsystem_cbus_out_xbar_state_3",
    "ldut_subsystem_cbus_out_xbar_state_4",
}



def _load_banks(path):
    if path is None:
        return None
    import json
    with open(path) as handle:
        data = json.load(handle)
    return {b["traceKey"]: b for b in data.get("banks", [])}

def load_entries(path: Path, expected=57) -> list[dict]:
    manifest = json.loads(path.read_text(encoding="utf-8"))
    entries = [
        entry for entry in manifest.get("oracles", [])
        if str(entry.get("flat", "")).startswith(PREFIX)
    ]
    if len(entries) != expected:
        raise ValueError(
            f"expected the locked contract's 57 PeripheryBus streams, got {len(entries)}"
        )
    keys = [entry["traceKey"] for entry in entries]
    if len(set(keys)) != len(keys):
        raise ValueError("duplicate PeripheryBus trace key in manifest")
    missing_legacy = sorted(LEGACY_KEYS.difference(keys))
    if missing_legacy:
        raise ValueError(
            "legacy PeripheryBus keys disappeared: " + ", ".join(missing_legacy)
        )
    kinds = {entry.get("kind") for entry in entries}
    if kinds != {"reg"}:
        raise ValueError(f"unsupported PeripheryBus oracle kinds: {sorted(kinds)}")
    return entries


def capture_expression(entry: dict, banks: dict | None = None) -> str:
    relative = entry["flat"].removeprefix(PREFIX)
    if relative == "fixer.flight__v2_bank_0_0" and (banks is None or entry["traceKey"] not in banks):
        return " | ".join(
            f"(word(state.fixer.flight_{index}) << {15 - index})"
            for index in range(16)
        )
    if banks is not None:
        bank = banks.get(entry["traceKey"])
        if bank is not None:
            terms = []
            for fld in bank["fields"]:
                src = fld["source"]
                rel = src.removeprefix(PREFIX)
                if rel == src:
                    raise ValueError(f"bank field outside module: {src}")
                width = fld["high"] - fld["low"] + 1
                mask = (1 << width) - 1
                terms.append(
                    f"((word(state.{rel}) & {hex(mask)}u) << {fld['low']})")
            return " | ".join(terms) if terms else "0"
        m = re.fullmatch(r"(.+)__w(\d+)", relative)
        if m is not None:
            base, wi = m.group(1), int(m.group(2))
            width = int(entry.get("width", 64))
            hi = 64 * wi + 63
            if wi > 0:
                return (f"static_cast<std::uint64_t>(state.{base}"
                        f".template bits<{hi}, {64 * wi}>().as_single_word())")
    return f"word(state.{relative})"


def capture_text(entries: list[dict], banks: dict | None = None) -> str:
    lines = [
        "// Auto-generated by generate_periphery_bus_oracle_bindings.py.",
        "// Manifest order is the public index contract.",
    ]
    for index, entry in enumerate(entries):
        lines.append(f"// [{index:2d}] {entry['traceKey']}")
        lines.append(
            f"periphery_bus_oracles[{index}] = {capture_expression(entry, banks)};"
        )
    return "\n".join(lines) + "\n"


def native_state_field(relative: str) -> str:
    """Bind an observation name to an existing software transaction field.

    This only describes storage geometry; it does not import RTL equations.
    Unknown fields fail the build rather than being silently filled with zero.
    """
    atomic = {"beatsLeft": "at_beats_left", "cam_a_0_bits_address": "cam_a.address",
              "cam_a_0_bits_size": "cam_a.size", "cam_a_0_bits_source": "cam_a.source",
              "cam_d_0_data": "cam_d_data", "cam_s_0_state": "cam_state",
              "d_first_counter": "at_d_first_counter", "state_0": "at_state0", "state_1": "at_state1"}
    if relative.startswith("atomics.") and relative[8:] in atomic:
        return "s." + atomic[relative[8:]]
    for prefix, name in [("buffer.bundleIn_0_d_q.", "buf_d"),
                         ("buffer.bundleOut_0_a_q.", "buf_a"),
                         ("wrapped_error_device.buffer.bundleIn_0_d_q.", "err_buf_d"),
                         ("wrapped_error_device.buffer.bundleOut_0_a_q.", "err_buf_a")]:
        if relative.startswith(prefix) and relative[len(prefix):] in {"maybe_full", "value", "value_1"}:
            return "s." + name + "." + relative[len(prefix):]
    match = re.fullmatch(r"coupler_to_(plic|clint|debug|bootrom)\.fragmenter\.(.+)", relative)
    if match:
        device, field = match.groups()
        member = f"s.frag[{['plic', 'clint', 'debug', 'bootrom'].index(device)}]."
        if field in {"aToggle_r", "acknum", "dOrig", "dToggle", "gennum"}:
            return member + field
        if field == "repeater_full":
            return member + "rep.full"
        if field.startswith("repeater_saved_") and field[15:] in {"address", "opcode", "size", "source"}:
            return member + "rep.saved." + field[15:]
        # Capture paths use a dot at the repeater instance boundary.
        if field.startswith("repeater."):
            return native_state_field(relative.replace("repeater.", "repeater_"))
    match = re.fullmatch(r"fixer\.flight_(\d+)", relative)
    if match:
        return f"((s.fx_flight >> {int(match[1])}) & 1u)"
    fixed = {"fixer.a_first_counter": "fx_a_first_counter", "fixer.stalls_id": "fx_stalls_id",
             "fixer.stalls_id_1": "fx_stalls_id_1", "out_xbar.beatsLeft": "xb_beats_left",
             "out_xbar.readys_mask": "xb_readys_mask", "wrapped_error_device.error.a.maybe_full": "err_q_maybe_full",
             "wrapped_error_device.error.a_last_counter": "err_a_last_counter"}
    if relative in fixed:
        return "s." + fixed[relative]
    match = re.fullmatch(r"out_xbar\.state_([0-4])", relative)
    if match:
        return f"((s.xb_state >> {int(match[1])}) & 1u)"
    match = re.fullmatch(r"wrapped_error_device\.error\.a\.ram_(opcode|size|source)", relative)
    if match:
        return "s.err_q_ram." + match[1]
    raise ValueError("PeripheryBus field has no native model binding: " + relative)


def native_capture_text(entries: list[dict], banks: dict | None = None) -> str:
    lines = ["// Native software-state projection; generated from the observation contract."]
    for index, entry in enumerate(entries):
        expression = capture_expression(entry, banks)
        expression = re.sub(r"word\(state\.([\w.]+)\)",
                            lambda m: "static_cast<std::uint64_t>(" + native_state_field(m[1]) + ")", expression)
        if "state." in expression or "word(" in expression:
            raise ValueError("unsupported native observation: " + expression)
        lines += [f"// {entry['traceKey']}", f"periphery_bus_oracles[{index}] = {expression};"]
    return "\n".join(lines) + "\n"


def bindings_text(entries: list[dict], expected_owned: int = 34) -> str:
    owned = [
        (index, entry) for index, entry in enumerate(entries)
        if entry["traceKey"] not in LEGACY_KEYS
    ]
    if len(owned) != expected_owned:
        raise ValueError(f"expected 34 newly owned PeripheryBus streams, got {len(owned)}")

    lines = [
        "// Auto-generated by generate_periphery_bus_oracle_bindings.py.",
        "// The 23 pre-existing CBus slots remain in the active-face batch.",
        f"static constexpr std::array<std::size_t, {len(owned)}>",
        "    kPeripheryBusSidecarOracleIndices = {",
    ]
    for offset in range(0, len(owned), 12):
        values = ", ".join(str(index) for index, _ in owned[offset:offset + 12])
        lines.append(f"        {values},")
    lines += [
        "};",
        "",
        "void sample_batch_periphery_bus_sidecar(const SystemGuider& model,",
        "                                         BatchSlots slots) {",
        "  const auto& values = model.fabric().periphery_bus_oracles();",
        "  for (std::size_t index = 0;",
        "       index < kPeripheryBusSidecarOracleIndices.size(); ++index)",
        "    batch_store(slots, index, values[kPeripheryBusSidecarOracleIndices[index]]);",
        "}",
        "",
        "void register_periphery_bus_sidecar_bindings() {",
        "  ModelBindings& bindings = ModelBindings::instance();",
    ]
    for owned_index, (_, entry) in enumerate(owned):
        prefix = "  const int base = " if owned_index == 0 else "  "
        lines.append(f"{prefix}bindings.reserve_sampled(")
        lines.append(f"      \"{entry['traceKey']}\");")
    lines += [
        "  bindings.add_batch_sampler(sample_batch_periphery_bus_sidecar, base);",
        "}",
    ]
    return "\n".join(lines) + "\n"


def write_or_check(path: Path, expected: str, check: bool) -> bool:
    actual = path.read_text(encoding="utf-8") if path.is_file() else None
    if actual == expected:
        return True
    if check:
        print(f"stale generated file: {path}")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    print(f"wrote {path}")
    return True


def main() -> int:
    root = Path(__file__).resolve().parents[3]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest", type=Path,
        default=root / "out/repcut-ae/chisa-small-v2-dead-pruned-extern/oracle_manifest.json",
    )
    parser.add_argument(
        "--capture-output", type=Path,
        default=root / "reference_models/boom-system/generated/periphery_bus_oracle_capture.inc",
    )
    parser.add_argument(
        "--bindings-output", type=Path,
        default=root / "reference_models/boom-system/generated/periphery_bus_oracle_bindings.inc",
    )
    parser.add_argument("--native-capture-output", type=Path,
                        default=root / "reference_models/boom-system/generated/periphery_bus_native_capture.inc")
    parser.add_argument("--expected-streams", type=int, default=57)
    parser.add_argument("--expected-owned", type=int, default=34)
    parser.add_argument("--bank-manifest", type=Path, default=None)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    try:
        entries = load_entries(args.manifest, args.expected_streams)
        good = write_or_check(
            args.capture_output, capture_text(entries, _load_banks(args.bank_manifest)), args.check
        )
        good &= write_or_check(args.native_capture_output,
                               native_capture_text(entries, _load_banks(args.bank_manifest)), args.check)
        good &= write_or_check(
            args.bindings_output, bindings_text(entries, args.expected_owned), args.check
        )
    except (OSError, KeyError, ValueError, json.JSONDecodeError) as error:
        parser.error(str(error))
    return 0 if good else 1


if __name__ == "__main__":
    raise SystemExit(main())
