#pragma once

#include <array>
#include <cstdint>
#include <cstdio>
#include <cstdlib>

#include "../../boom_model/common/boom_config.h"
#include "async_queue.h"

namespace chisa::boom_system::components {

/** One LSU request entering the full-chip DCache request pipeline. */
struct BoomUncachedRequest {
  bool valid = false;
  bool uses_ldq = false;
  bool uses_stq = false;
  bool is_amo = false;
  bool is_signed = false;
  boomcfg::br_mask_t br_mask = 0;
  std::uint8_t ldq_idx = 0;
  std::uint8_t stq_idx = 0;
  std::uint8_t command = 0;
  std::uint8_t size = 0;
  std::uint64_t address = 0;
  std::uint64_t data = 0;
  // True for the PTW/RoCC HellaCache seam.  These requests do not name an
  // LSQ entry, so the tag must survive D-cache hits, nacks and MSHR replay
  // independently of uses_ldq/uses_stq.
  bool is_hella = false;
};

/** LSU-visible completion generated by the DCache. */
struct BoomUncachedCompletion {
  bool valid = false;
  std::uint64_t data = 0;
  bool uses_ldq = false;
  bool uses_stq = false;
  std::uint8_t ldq_idx = 0;
  std::uint8_t stq_idx = 0;
  bool is_hella = false;
  bool is_amo = false;   // respq uop lane read across the dcache cut
};

/** One request offered by the external DMI transport. */
struct BoomDmiRequest {
  bool valid = false;
  std::uint8_t address = 0;
  std::uint8_t operation = 0;
  std::uint32_t data = 0;
};

/** Cycle-start remote signals presented to TLDebugModuleOuterAsync's three
  * live asynchronous endpoints. Payload interpretation remains in the fixed
  * sidecar seam; this record only owns the crossing boundary. */
struct DebugOuterCrossingInputs {
  bool a_ridx = false;
  bool a_ridx_valid = false;
  bool a_sink_reset_n = false;
  std::uint64_t d_memory = 0;
  bool d_widx = false;
  bool d_widx_valid = false;
  bool d_source_reset_n = false;
  bool inner_ctrl_ridx = false;
  bool inner_ctrl_ridx_valid = false;
  bool inner_ctrl_sink_reset_n = false;
  bool hg_debug_int = false;
};

/** Combinational view before the next modeled core edge.
  *
  * The fabric-stage fields are observability aids for artifact differential
  * tests.  The producer contract used by BoomGuider is `response` plus
  * `nack`; neither is derived from a DUT tap. */
struct BoomUncachedOutputs {
  BoomUncachedCompletion response{};
  BoomUncachedCompletion nack{};

  bool iomshr_req_valid = false;
  bool iomshr_req_ready = false;
  std::uint8_t iomshr_state = 0;
  bool dcache_s1_valid = false;
  bool dcache_s2_valid = false;
  bool s2_store_ack = false;

  bool dcache_a_valid = false;
  std::uint8_t dcache_a_opcode = 0;
  std::uint8_t dcache_a_size = 0;
  // BoomMSHR sources occupy 0..nMSHRs-1 and the writeback unit owns
  // nMSHRs; the sole IOMSHR is therefore nMSHRs+1 (3 on Small, 5 on Large).
  std::uint8_t dcache_a_source = boomcfg::DCACHE_MSHRS + 1;
  std::uint32_t dcache_a_address = 0;
  std::uint8_t dcache_a_mask = 0;
  std::uint64_t dcache_a_data = 0;
  bool tile_a_valid = false;
  bool debug_a_valid = false;
  bool tile_d_valid = false;
  bool dcache_d_valid = false;
  std::uint64_t fabric_address = 0;
  std::uint64_t fabric_data = 0;

  bool halted = false;
  bool resume_requested = false;
  bool go = false;
  bool go_abstract = false;
  bool abstract_busy = false;
  bool dmi_req_ready = false;
  bool dmi_resp_valid = false;
  std::uint8_t dmi_resp_response = 0;
  std::uint32_t dmi_resp_data = 0;
  bool dmi_inner_ready = false;
  bool inner_ctrl_ready = false;
  std::uint64_t abstract_data = 0;
};

struct BoomUncachedPathInputs {
  bool reset = false;
  BoomUncachedRequest request{};
  BoomDmiRequest dmi{};
  bool dmi_response_ready = false;
  // The coherent MSHRs have priority over the IOMSHR on DCache A.  Standalone
  // users have no competing client, so preserve the former always-ready
  // behavior by default.
  bool tile_a_ready = true;
  // D-channel response returned by the shared full-chip fabric.  Source
  // nMSHRs+1 is the BoomIOMSHR; coherent MSHR responses are consumed by
  // SmallDcache.
  bool tile_d_valid = false;
  std::uint8_t tile_d_opcode = 0;
  std::uint8_t tile_d_source = 0;
  std::uint64_t tile_d_data = 0;

  // Accepted request at the Debug Module's CBus manager face. Medium/Large's
  // path crosses the live SystemBus/PeripheryBus before reaching dmInner, so
  // Debug register-router side effects occur on this A-channel handshake,
  // not when the response later returns to the IOMSHR on D.
  bool debug_manager_a_fire = false;
  std::uint8_t debug_manager_a_source = 0;
};

/** Locked SmallBoom uncached path for the hart-facing Debug Module window.
  *
  * This models the exercised path, rather than a generic latency queue:
  *
  *   LSU -> DCache s1/s2 -> the single BoomIOMSHR -> TileLink -> Debug Module
  *
  * The IOMSHR is the four-state machine emitted by `mshrs.scala`: idle,
  * mem_access, wait_ack, response.  A store is acknowledged to the LSU when
  * it allocates the IOMSHR in DCache s2, while a load response returns one
  * cycle after the IOMSHR response state.  A request reaching s2 while the
  * sole IOMSHR is busy receives a tagged nack.
  *
  * The fixed TileLink stages are those in the locked Small artifact.  They
  * are not intended to stand in for the other uncached managers; requests
  * supplied to this component must belong to the 0x000--0xfff Debug window.
  */
class BoomUncachedPath {
 public:
  static constexpr std::uint8_t kIomshrSource =
      static_cast<std::uint8_t>(boomcfg::DCACHE_MSHRS + 1);
  enum class IomshrState : std::uint8_t {
    kIdle = 0,
    kMemAccess = 1,
    kWaitAck = 2,
    kResponse = 3,
  };

  void reset() { *this = BoomUncachedPath{}; }

  BoomUncachedOutputs outputs() const {
    return outputs(BoomUncachedPathInputs{});
  }

  BoomUncachedOutputs outputs(const BoomUncachedPathInputs& input) const {

    BoomUncachedOutputs result;

    outputs_into(input, result);

    return result;

  }

  void outputs_into(const BoomUncachedPathInputs& input, BoomUncachedOutputs& result) const {
    result = BoomUncachedOutputs{};
    result.iomshr_state = static_cast<std::uint8_t>(state_);
    result.iomshr_req_valid = s2_.valid;
    result.iomshr_req_ready = state_ == IomshrState::kIdle;
    result.dcache_s1_valid = s1_.valid;
    result.dcache_s2_valid = s2_.valid;
    result.fabric_address = active_.address;
    result.fabric_data = fabric_data_;
    result.halted = halted_;
    result.resume_requested = resume_requested_;
    result.go = go_;
    result.go_abstract = go_armed_;
    result.abstract_busy = abstract_busy_;
    result.dmi_inner_ready = dmi_request_queue_.source().enq_ready();
    result.inner_ctrl_ready = inner_ctrl_queue_.source().enq_ready();
    result.abstract_data = abstract_data_;
    result.dcache_a_opcode = returns_data(active_.command) ? 4 : 0;
    result.dcache_a_size = active_.size;
    result.dcache_a_source = kIomshrSource;
    result.dcache_a_address = static_cast<std::uint32_t>(active_.address);
    result.dcache_a_mask = request_mask(active_.address, active_.size);
    result.dcache_a_data = active_.data;

    const std::uint8_t routed_dmi_address = dmi_routed_address(input.dmi);
    const bool request_targets_outer =
        is_outer_dmi_address(routed_dmi_address);
    result.dmi_req_ready = request_targets_outer
                               ? input.dmi_response_ready
                               : dmi_request_queue_.source().enq_ready();
    if (input.dmi.valid && request_targets_outer) {
      // dmOuter is a combinational RegisterRouter.  Its one-beat response is
      // returned in the request cycle, and backpressure on DMI response is
      // therefore also backpressure on the request.
      result.dmi_resp_valid = true;
      result.dmi_resp_data = outer_dmi_read(routed_dmi_address);
    } else {
      // With no live outer request, an independently delayed dmInner response
      // must remain visible even though invalid DMI payload bits conventionally
      // decode as a NOP/HARTINFO transaction.
      result.dmi_resp_valid = dmi_response_queue_.sink().deq_valid();
      if (result.dmi_resp_valid) {
        const std::uint64_t bits = dmi_response_queue_.sink().deq_bits();
        result.dmi_resp_data = static_cast<std::uint32_t>(bits);
        result.dmi_resp_response = static_cast<std::uint8_t>((bits >> 32) & 3);
      }
    }

    result.dcache_a_valid = state_ == IomshrState::kMemAccess;
    if (state_ == IomshrState::kWaitAck) {
      result.tile_a_valid = fabric_countdown_ == 3;
      result.debug_a_valid = fabric_countdown_ == 2;
      result.tile_d_valid = fabric_countdown_ == 1;
      result.dcache_d_valid = fabric_countdown_ == 0;
    }

    if (s2_.valid) {
      if (state_ != IomshrState::kIdle) {
        result.nack = completion_for(s2_, 0);
      } else if (!returns_data(s2_.command)) {
        result.response = completion_for(s2_, 0);
        result.s2_store_ack = true;
      }
    }
    if (lsu_response_.valid) result.response = lsu_response_;
    return;
  }

  /** Read the hart-facing Debug Module memory map used for instruction
    * refills.  This storage is owned by the Debug Module model; the shared
    * TileLink producer only supplies protocol and queue state. */
  std::uint64_t debug_memory_read64(std::uint32_t address) const {
    std::uint64_t result = 0;
    for (unsigned byte = 0; byte < 8; ++byte)
      result |= static_cast<std::uint64_t>(
                    debug_memory_read8(address + byte))
                << (byte * 8u);
    return result;
  }

  void step(const BoomUncachedPathInputs& input) {
    entered_resp_now_ = false;
    if (input.reset) {
      reset();
      inner_ctrl_source_inputs_oracle_.reset = true;
      debug_inner_clock_edge_oracle_ = true;
      return;
    }

    // Snapshot the gated debug-clock decision before the handshake below
    // advances to its next value.  A generated dmInner sidecar consumes this
    // exact edge enable; dmOuter remains on the always-running DMI clock.
    debug_inner_clock_edge_oracle_ = inner_clock_enabled_;
    // goReg/resumereq are REGISTERS: a same-cycle goAbstract (go_armed_->go_
    // below) sets them for the FOLLOWING edge, so a debug-flags read serviced
    // this cycle must see their start-of-cycle (registered) value, not the
    // value updated a few statements later.  Snapshot them here.
    go_registered_ = go_;
    resume_registered_ = resume_requested_;

    // A registered LSU response is presented for exactly one cycle.
    lsu_response_.valid = false;

    // `goAbstract` is a one-cycle combinational state-machine output.  Its
    // value at this edge sets goReg for the following cycle.
    if (go_armed_) {
      go_ = true;
      go_armed_ = false;
    }
    if (reject_armed_) {
      abstract_busy_ = false;
      abstract_cmderr_ = 2;
      reject_armed_ = false;
    }

    const bool inner_dmi_valid = dmi_request_queue_.sink().deq_valid();
    const std::uint64_t inner_dmi_bits =
        dmi_request_queue_.sink().deq_bits();
    const bool inner_dmi_ready =
        dmi_response_queue_.source().enq_ready();
    const bool inner_dmi_fire =
        inner_clock_enabled_ && inner_dmi_valid && inner_dmi_ready;
    const bool abstract_busy_before_inner_dmi = abstract_busy_;
    std::uint64_t inner_dmi_response = 0;
    if (inner_dmi_fire) {
      const std::uint8_t operation = (inner_dmi_bits >> 39) & 0x3;
      const std::uint8_t tl_opcode = operation == 1 ? 1 : 0;
      inner_dmi_response = pack_dmi_response(
          service_inner_dmi(inner_dmi_bits), 0, tl_opcode);
    }
    const bool abstract_started_by_inner_dmi =
        !abstract_busy_before_inner_dmi && abstract_busy_;
    if (inner_clock_enabled_ && inner_ctrl_queue_.sink().deq_valid() &&
        (inner_ctrl_queue_.sink().deq_bits() & 1u)) {
      resume_requested_ = true;
    }

    {
      static const bool trace = std::getenv("CHISA_DMI_TRACE") != nullptr;
      static long long steps = 0;
      ++steps;
      static int shown = 0;
      if (trace && shown < 60 &&
          (state_ != IomshrState::kIdle || s2_.valid)) {
        ++shown;
        std::fprintf(stderr,
                     "[IOM k%lld] st=%d s2v=%d addr=%llx cmd=%u a_rdy=%d "
                     "d_v=%d d_src=%u cd=%u\n",
                     steps, (int)state_, (int)s2_.valid,
                     (unsigned long long)(state_ == IomshrState::kIdle
                                              ? s2_.address
                                              : active_.address),
                     (unsigned)active_.command, (int)input.tile_a_ready,
                     (int)input.tile_d_valid, (unsigned)input.tile_d_source,
                     (unsigned)fabric_countdown_);
      }
    }
    switch (state_) {
      case IomshrState::kIdle:
        if (s2_.valid) {
          active_ = s2_;
          state_ = IomshrState::kMemAccess;
        }
        break;

      case IomshrState::kMemAccess:
        if (input.tile_a_ready) {
          state_ = IomshrState::kWaitAck;
          fabric_countdown_ = 3;
        }
        break;

      case IomshrState::kWaitAck:
        if (belongs_to_debug_window(active_.address)) {
          // Preserve the independently qualified Debug Module timing.  The
          // hand-written debug state and extracted dmInner advance together,
          // but the former owns architectural halt/resume side effects.
          if constexpr (boomcfg::CORE_WIDTH == 1) {
            if (fabric_countdown_ == 2)
              service_debug_request(abstract_started_by_inner_dmi);
          }
          if constexpr (boomcfg::CORE_WIDTH != 1) {
            // Medium/Large use the actual queued tile/fabric path rather
            // than the locked Small fixed-latency shortcut. In dmInner the
            // register router commits every write notification on its manager
            // A handshake.  In particular, RESUMING clears haltedBitRegs and
            // resumeReqRegs before a concurrent DMSTATUS response is formed;
            // waiting for the returning D beat makes that response observe the
            // stale halted state.  The D beat only retires the IOMSHR (and
            // carries read data) after the write side effect has happened.
            if (fabric_countdown_ != 0) --fabric_countdown_;
            if (input.debug_manager_a_fire &&
                (input.debug_manager_a_source >> 4) == kIomshrSource)
              service_debug_request(abstract_started_by_inner_dmi);
            if (input.tile_d_valid &&
                input.tile_d_source == kIomshrSource) {
              if (returns_data(active_.command))
                grant_word_ = input.tile_d_data;
              state_ = IomshrState::kResponse;
            }
          } else if (fabric_countdown_ == 0) {
            // mshrs.scala:463 grant_word is written only for reads.
            if (returns_data(active_.command)) grant_word_ = fabric_data_;
            state_ = IomshrState::kResponse;
          } else {
            --fabric_countdown_;
          }
        } else if (input.tile_d_valid &&
                   input.tile_d_source == kIomshrSource) {
          // Full-chip MMIO (PLIC, CLINT and the external MMIO manager) must
          // wait for the real cold-fabric D beat.  No fixed-latency shortcut
          // is valid across these independently queued managers.
          if (returns_data(active_.command))
            grant_word_ = input.tile_d_data;
          state_ = IomshrState::kResponse;
        }
        break;

      case IomshrState::kResponse:
        if (returns_data(active_.command)) {
          lsu_response_ = completion_for(
              active_, extract_load(grant_word_, active_.address,
                                    active_.size, active_.is_signed));
          entered_resp_now_ = true;
        }
        state_ = IomshrState::kIdle;
        break;
    }

    iomshr_state_oracle_ = iomshr_state_now();

    // NonBlockingDCache request pipeline: a request accepted on edge T is in
    // s2 (and can ack/nack/allocate) before edge T+2.
    s2_ = s1_;
    s1_ = input.request;

    // The first dmactive write releases the clock/reset handshake around
    // dmInner.  The two three-register synchronizers are the reason early
    // DMCONTROL reads do not expose bit zero until edge 23 in the locked
    // bootstrap trace, while the first inner request is not ready until edge
    // 32.
    const bool debug_reset_syncd = !reset_sync_0_;
    const bool reset_sync_2_next = true;
    const bool reset_sync_1_next = reset_sync_2_;
    const bool reset_sync_0_next = reset_sync_1_;
    const bool top_ack_sync_2_next =
        !debug_reset_syncd && dmactive_;
    const bool top_ack_sync_1_next = top_ack_sync_2_;
    const bool top_ack_sync_0_next = top_ack_sync_1_;
    const bool outer_ack_sync_2_next = top_ack_sync_0_;
    const bool outer_ack_sync_1_next = outer_ack_sync_2_;
    const bool outer_ack_sync_0_next = outer_ack_sync_1_;
    const bool inner_clock_enabled_next =
        debug_reset_syncd || top_ack_sync_0_;
    bool inner_dmactive_sync_2_next = inner_dmactive_sync_2_;
    bool inner_dmactive_sync_1_next = inner_dmactive_sync_1_;
    bool inner_dmactive_sync_0_next = inner_dmactive_sync_0_;
    if (inner_clock_enabled_) {
      inner_dmactive_sync_2_next = !debug_reset_syncd && dmactive_;
      inner_dmactive_sync_1_next = inner_dmactive_sync_2_;
      inner_dmactive_sync_0_next = inner_dmactive_sync_1_;
    }

    const std::uint8_t routed_dmi_address = dmi_routed_address(input.dmi);
    // dmi_req_ready of the cycle face: an outer request is ready when the
    // response side is, an inner one when the request crossing can enqueue
    // (neither endpoint has advanced yet at this point of the step).
    const bool dmi_req_ready_now =
        is_outer_dmi_address(routed_dmi_address)
            ? input.dmi_response_ready
            : dmi_request_queue_.source().enq_ready();
    const bool outer_dmi_fire =
        input.dmi.valid && is_outer_dmi_address(routed_dmi_address) &&
        dmi_req_ready_now;
    if (outer_dmi_fire && input.dmi.operation == 2 &&
        input.dmi.address == UINT8_C(0x10)) {
      service_dmcontrol_write(input.dmi.data);
    }

    // DMCONTROL and HARTINFO live in dmOuter.  All other exercised DMI
    // registers traverse the locked pair of depth-one TLAsyncCrossings.
    const bool route_to_inner =
        input.dmi.valid && !is_outer_dmi_address(routed_dmi_address);
    // The AsyncQueue endpoints in dmInner reset from io_debug_reset, not from
    // the later dmactive synchronizer.  The latter synchronously clears the
    // Debug Module registers, but delaying the crossing safe-start with it
    // makes the first inner request three cycles late (35 instead of 32).
    const bool inner_debug_reset = debug_reset_syncd;
    // Snapshot every remote endpoint before either side advances. Async reset
    // is reflected immediately, even though the hand-written queue's step is
    // performed a few statements later on this same host edge.
    debug_outer_crossing_inputs_oracle_ = DebugOuterCrossingInputs{
        inner_debug_reset ? false : dmi_request_queue_.sink().async_ridx(),
        inner_debug_reset
            ? false
            : dmi_request_queue_.sink().async_ridx_valid(),
        !inner_debug_reset,
        dmi_response_queue_.source().memory(),
        inner_debug_reset ? false : dmi_response_queue_.source().async_widx(),
        inner_debug_reset
            ? false
            : dmi_response_queue_.source().async_widx_valid(),
        !inner_debug_reset,
        inner_debug_reset ? false : inner_ctrl_queue_.sink().async_ridx(),
        inner_debug_reset
            ? false
            : inner_ctrl_queue_.sink().async_ridx_valid(),
        !inner_debug_reset,
        false};
    // dmOuter's DMI crossbar D-channel arbiter (TLArbiter round-robin over
    // the two responders: bit 1 = the outer register block, whose register
    // router answers in the same cycle as the request, bit 0 = the bypass
    // bar, i.e. the inner crossing's response sink).  Transcribed from the
    // generated TLXbar: filter = {valids & ~mask, valids}, unready =
    // (rightOR2(filter) >> 1) | (mask << 2), readys = ~(unready[3:2] &
    // unready[1:0]); when idle and the DMI response is accepted, mask :=
    // grant | grant << 1.  A DMI transfer is single-beat, so idle holds.
    {
      const unsigned valid_outer = (input.dmi.valid &&
                                    is_outer_dmi_address(routed_dmi_address)) ? 2u : 0u;
      const unsigned valid_bar =
          (!bypass_reg_ && dmi_response_queue_.sink().deq_valid()) ? 1u : 0u;
      const unsigned valids = valid_outer | valid_bar;
      const unsigned mask = dmi_xbar_readys_mask_ & 3u;
      const unsigned filter = ((valids & ~mask & 3u) << 2) | valids;
      const unsigned right_or = filter | (filter >> 1);
      const unsigned unready = ((right_or >> 1) | (mask << 2)) & 0xfu;
      const unsigned readys = ~((unready >> 2) & unready) & 3u;
      if (input.reset) {
        dmi_xbar_readys_mask_ = 3;
      } else if (input.dmi_response_ready && valids != 0) {
        const unsigned grant = readys & valids;
        dmi_xbar_readys_mask_ =
            static_cast<std::uint8_t>((grant | (grant << 1)) & 3u);
      }
      bypass_reg_ = !dmactive_ || !outer_ack_sync_0_;
    }
    dmi_request_queue_.step_gated(
        input.reset, inner_debug_reset, true, inner_clock_enabled_,
        route_to_inner, pack_dmi(input.dmi), inner_dmi_ready);
    dmi_response_queue_.step_gated(
        inner_debug_reset, input.reset, inner_clock_enabled_, true,
        inner_dmi_fire, inner_dmi_response, input.dmi_response_ready);
    const bool inner_ctrl_event =
        outer_dmi_fire && input.dmi.operation == 2 &&
        input.dmi.address == UINT8_C(0x10);
    const std::uint64_t inner_ctrl_event_bits =
        static_cast<std::uint64_t>((input.dmi.data >> 30) & 1u);
    // dmOuter's Decoupled producer retains an inner-control update until the
    // asynchronous source can accept it.  A one-cycle DMI write pulse is not
    // itself the queue boundary: dropping `valid` while `ready` is low loses
    // the first dmactive update during safe-start.
    const bool inner_ctrl_valid =
        inner_ctrl_event || inner_ctrl_valid_reg_;
    const std::uint64_t inner_ctrl_bits =
        inner_ctrl_event ? inner_ctrl_event_bits : inner_ctrl_bits_reg_;
    const bool inner_ctrl_ready =
        inner_ctrl_queue_.source().enq_ready();
    // Snapshot the source endpoint boundary before either endpoint advances.
    // The payload is intentionally opaque here; ready_reg depends only on
    // valid and the remote pointer/safe-start signals. The generated sidecar
    // exposes only that selected control register in this first integration.
    inner_ctrl_source_inputs_oracle_ = AsyncQueueSourceInputs{
        input.reset,
        inner_ctrl_valid,
        inner_ctrl_bits,
        inner_ctrl_queue_.sink().async_ridx(),
        inner_ctrl_queue_.sink().async_ridx_valid(),
        !inner_debug_reset};
    inner_ctrl_queue_.step_gated(
        input.reset, inner_debug_reset, true, inner_clock_enabled_,
        inner_ctrl_valid, inner_ctrl_bits, true);
    inner_ctrl_valid_reg_ = inner_ctrl_valid && !inner_ctrl_ready;
    if (inner_ctrl_valid_reg_) inner_ctrl_bits_reg_ = inner_ctrl_bits;

    reset_sync_2_ = reset_sync_2_next;
    reset_sync_1_ = reset_sync_1_next;
    reset_sync_0_ = reset_sync_0_next;
    top_ack_sync_2_ = top_ack_sync_2_next;
    top_ack_sync_1_ = top_ack_sync_1_next;
    top_ack_sync_0_ = top_ack_sync_0_next;
    outer_ack_sync_2_ = outer_ack_sync_2_next;
    outer_ack_sync_1_ = outer_ack_sync_1_next;
    outer_ack_sync_0_ = outer_ack_sync_0_next;
    inner_clock_enabled_ = inner_clock_enabled_next;
    inner_dmactive_sync_2_ = inner_dmactive_sync_2_next;
    inner_dmactive_sync_1_ = inner_dmactive_sync_1_next;
    inner_dmactive_sync_0_ = inner_dmactive_sync_0_next;
  }

 private:
  static bool belongs_to_debug_window(std::uint64_t address) {
    return address < UINT64_C(0x1000);
  }

  static bool returns_data(std::uint8_t command) {
    // M_XRD, M_XLR, M_XSC, and the AMO command range.  This is the exact
    // `_T_64` classification emitted in BoomIOMSHR.
    return command == 0 || command == 6 || command == 7 ||
           (command >= 8 && command <= 15);
  }

  static std::uint8_t request_mask(std::uint64_t address,
                                   std::uint8_t size) {
    const unsigned bytes = size >= 3 ? 8u : 1u << size;
    const unsigned lane = static_cast<unsigned>(address & 7u);
    return static_cast<std::uint8_t>(
        ((UINT16_C(1) << bytes) - 1u) << lane);
  }

  static BoomUncachedCompletion completion_for(
      const BoomUncachedRequest& request, std::uint64_t data) {
    return BoomUncachedCompletion{true,
                                  data,
                                  request.uses_ldq,
                                  request.uses_stq,
                                  request.ldq_idx,
                                  request.stq_idx,
                                  request.is_hella,
                                  request.is_amo};
  }

  static std::uint64_t pack_dmi(const BoomDmiRequest& request) {
    return static_cast<std::uint64_t>(request.data) |
           (static_cast<std::uint64_t>(request.address & 0x7f) << 32) |
           (static_cast<std::uint64_t>(request.operation & 0x3) << 39);
  }

  static std::uint64_t pack_dmi_response(std::uint32_t data,
                                         std::uint8_t response = 0,
                                         std::uint8_t tl_opcode = 1) {
    return static_cast<std::uint64_t>(data) |
           (static_cast<std::uint64_t>(response & 3) << 32) |
           (static_cast<std::uint64_t>(tl_opcode & 7) << 34);
  }

  static bool is_outer_dmi_address(std::uint8_t address) {
    return address == UINT8_C(0x10) || address == UINT8_C(0x12);
  }

  static std::uint8_t dmi_routed_address(const BoomDmiRequest& request) {
    // DMIToTL turns every NOP into a Put to the read-only HARTINFO register.
    // This guarantees a response without crossing into dmInner, which may be
    // clock-gated or held in reset.  Routing on the request's raw addr would
    // incorrectly enqueue the conventional addr=0 NOP into dmInner.
    return request.operation == 0 ? UINT8_C(0x12) : request.address;
  }

  std::uint32_t dmcontrol_read() const {
    return (static_cast<std::uint32_t>(halt_request_) << 31) |
           (static_cast<std::uint32_t>(ndmreset_) << 1) |
           static_cast<std::uint32_t>(dmactive_ && outer_ack_sync_0_);
  }

  std::uint32_t outer_dmi_read(std::uint8_t address) const {
    if (address == UINT8_C(0x10)) return dmcontrol_read();
    if (address == UINT8_C(0x12)) return UINT32_C(0x00112380);
    return 0;
  }

  void service_dmcontrol_write(std::uint32_t data) {
    const bool was_active = dmactive_;
    if (was_active) {
      halt_request_ = ((data >> 31) & 1u) != 0;
      ndmreset_ = ((data >> 1) & 1u) != 0;
    } else {
      halt_request_ = false;
      ndmreset_ = false;
    }
    dmactive_ = (data & 1u) != 0;
    if (!dmactive_) {
      halt_request_ = false;
      ndmreset_ = false;
    }
  }

  std::uint32_t service_inner_dmi(std::uint64_t bits) {
    const std::uint8_t operation = (bits >> 39) & 0x3;
    const std::uint8_t address = (bits >> 32) & 0x7f;
    const std::uint32_t data = bits & UINT64_C(0xffffffff);
    const std::uint32_t response_data = inner_dmi_read(address);
    if (operation != 2) return response_data;
    ++debug_register_version_;

    if (address == UINT8_C(0x04)) {
      abstract_data_ = (abstract_data_ & UINT64_C(0xffffffff00000000)) | data;
      if (abstract_auto_data_ & UINT8_C(1)) start_abstract_command();
      return response_data;
    }
    if (address == UINT8_C(0x05)) {
      abstract_data_ = (abstract_data_ & UINT64_C(0x00000000ffffffff)) |
                       (static_cast<std::uint64_t>(data) << 32);
      if (abstract_auto_data_ & UINT8_C(2)) start_abstract_command();
      return response_data;
    }
    if (address == UINT8_C(0x16)) {
      if (data & UINT32_C(0x700)) abstract_cmderr_ = 0;
      return response_data;
    }
    if (address == UINT8_C(0x18)) {
      abstract_auto_data_ = data & UINT8_C(3);
      return response_data;
    }
    if (address >= UINT8_C(0x20) && address < UINT8_C(0x30)) {
      program_buffer_[address - UINT8_C(0x20)] = data;
      return response_data;
    }
    if (address != UINT8_C(0x17)) return response_data;

    access_register_command_ = data;
    start_abstract_command();
    return response_data;
  }

  std::uint32_t inner_dmi_read(std::uint8_t address) const {
    if (address == UINT8_C(0x04))
      return static_cast<std::uint32_t>(abstract_data_);
    if (address == UINT8_C(0x05))
      return static_cast<std::uint32_t>(abstract_data_ >> 32);
    if (address == UINT8_C(0x11)) {
      const std::uint32_t run_state =
          halted_ ? UINT32_C(0x00000300) : UINT32_C(0x00000c00);
      const std::uint32_t resume_ack =
          resume_requested_ ? 0 : UINT32_C(0x00030000);
      return UINT32_C(0x000000a2) | run_state | resume_ack;
    }
    if (address == UINT8_C(0x16)) {
      return UINT32_C(0x10000002) |
             (static_cast<std::uint32_t>(abstract_busy_) << 12) |
             (static_cast<std::uint32_t>(abstract_cmderr_ & 7) << 8);
    }
    if (address == UINT8_C(0x17)) return access_register_command_;
    if (address == UINT8_C(0x18)) return abstract_auto_data_;
    if (address >= UINT8_C(0x20) && address < UINT8_C(0x30))
      return program_buffer_[address - UINT8_C(0x20)];
    return 0;
  }

  void start_abstract_command() {
    if (abstract_busy_ || abstract_cmderr_ != 0) return;
    const std::uint32_t data = access_register_command_;

    // Access Register is command type zero.  The locked RV64 abstract engine
    // accepts aarsize=3; the first FESVR probe deliberately tries aarsize=4
    // and spends one cycle in the error path without asserting goAbstract.
    const std::uint8_t command_type = data >> 24;
    const std::uint8_t aarsize = (data >> 20) & 0x7;
    const bool transfer = ((data >> 17) & 1u) != 0;
    const bool supported = command_type == 0 && aarsize == 3 && transfer &&
                           halted_ && !resume_requested_;
    abstract_busy_ = true;
    if (supported) {
      abstract_generated_[0] = generated_transfer_instruction(data);
      abstract_generated_[1] = ((data >> 18) & 1u) != 0
                                   ? UINT32_C(0x00000013)  // NOP
                                   : UINT32_C(0x00100073); // EBREAK
      go_armed_ = true;
    } else {
      reject_armed_ = true;
    }
  }

  static std::uint64_t extract_load(std::uint64_t word,
                                    std::uint64_t address,
                                    std::uint8_t size, bool is_signed) {
    const unsigned bytes = size >= 3 ? 8u : 1u << size;
    const unsigned shift = static_cast<unsigned>(address & 7u) * 8u;
    std::uint64_t value = word >> shift;
    if (bytes == 8) return value;
    const unsigned bits = bytes * 8u;
    const std::uint64_t mask = (UINT64_C(1) << bits) - 1;
    value &= mask;
    if (is_signed && ((value >> (bits - 1)) & 1u)) value |= ~mask;
    return value;
  }

  static std::uint32_t generated_transfer_instruction(
      std::uint32_t command) {
    const std::uint32_t size = (command >> 20) & 7u;
    const std::uint32_t regno = command & 0x1fu;
    const bool write_register = ((command >> 16) & 1u) != 0;
    constexpr std::uint32_t data_address = UINT32_C(0x380);
    if (write_register) {
      // I-type load: DATA(x0) -> selected architectural register.
      return (data_address << 20) | (size << 12) | (regno << 7) |
             UINT32_C(0x03);
    }

    // S-type store: selected architectural register -> DATA(x0).
    return ((data_address >> 5) << 25) | (regno << 20) |
           (size << 12) | ((data_address & 0x1fu) << 7) |
           UINT32_C(0x23);
  }

  std::uint8_t debug_memory_read8(std::uint32_t address) const {
    constexpr std::uint32_t whereto = UINT32_C(0x0380006f);
    if (address >= UINT32_C(0x300) && address < UINT32_C(0x304))
      return static_cast<std::uint8_t>(
          whereto >> ((address - UINT32_C(0x300)) * 8u));

    if (address >= UINT32_C(0x338) && address < UINT32_C(0x340)) {
      const unsigned offset = address - UINT32_C(0x338);
      return static_cast<std::uint8_t>(
          abstract_generated_[offset / 4u] >> ((offset & 3u) * 8u));
    }

    if (address >= UINT32_C(0x340) && address < UINT32_C(0x380)) {
      const unsigned offset = address - UINT32_C(0x340);
      return static_cast<std::uint8_t>(
          program_buffer_[offset / 4u] >> ((offset & 3u) * 8u));
    }

    if (address >= UINT32_C(0x380) && address < UINT32_C(0x388))
      return static_cast<std::uint8_t>(
          abstract_data_ >> ((address - UINT32_C(0x380)) * 8u));

    if (address >= UINT32_C(0x400) && address < UINT32_C(0x800))
      return static_cast<std::uint8_t>(
          (static_cast<unsigned>(resume_requested_) << 1) |
          static_cast<unsigned>(go_));

    if (address >= UINT32_C(0x800) &&
        address < UINT32_C(0x800) + kDebugRom.size())
      return kDebugRom[address - UINT32_C(0x800)];
    return 0;
  }

  std::uint64_t debug_read(std::uint64_t address) const {
    if ((address & ~UINT64_C(7)) == UINT64_C(0x380))
      return abstract_data_;
    if ((address & ~UINT64_C(7)) == UINT64_C(0x400)) {
      const std::uint64_t byte =
          (static_cast<std::uint64_t>(resume_registered_) << 1) |
          static_cast<std::uint64_t>(go_registered_);
      return byte * UINT64_C(0x0101010101010101);
    }
    return 0;
  }

  void service_debug_request(bool abstract_started_this_edge) {
    // Looked up once: getenv walks the environment block on every call.
    static const bool ctrl_trace = std::getenv("CHISA_DEBUG_CTRL_TRACE") != nullptr;
    if (ctrl_trace) {
      std::fprintf(stderr,
                   "[DEBUG-CTRL] addr=%llx cmd=%u busy=%u go=%u "
                   "started=%u state=%u\n",
                   static_cast<unsigned long long>(active_.address),
                   static_cast<unsigned>(active_.command),
                   static_cast<unsigned>(abstract_busy_),
                   static_cast<unsigned>(go_),
                   static_cast<unsigned>(abstract_started_this_edge),
                   static_cast<unsigned>(state_));
    }
    if (returns_data(active_.command)) {
      fabric_data_ = debug_read(active_.address);
      return;
    }

    if ((active_.address & ~UINT64_C(7)) == UINT64_C(0x380)) {
      const std::uint64_t before = abstract_data_;
      const unsigned bytes = active_.size >= 3 ? 8u : 1u << active_.size;
      const unsigned first = static_cast<unsigned>(active_.address & 7u);
      for (unsigned offset = 0; offset < bytes && first + offset < 8;
           ++offset) {
        const unsigned bit = (first + offset) * 8u;
        const std::uint64_t mask = UINT64_C(0xff) << bit;
        abstract_data_ = (abstract_data_ & ~mask) |
                         (active_.data & mask);
      }
      // The hart writes DATA0/DATA1 through TileLink too. The publication
      // cache must see those writes, not just writes arriving through DMI.
      if (abstract_data_ != before) ++debug_register_version_;
      fabric_data_ = 0;
      return;
    }

    // Hart debug-ROM notifications.  The locked single-hart router only
    // accepts a full 32-bit notification word; hart id zero is exercised.
    switch (active_.address & ~UINT64_C(3)) {
      case UINT64_C(0x100):  // HALTED
        halted_ = true;
        // The Debug ROM writes HALTED once while it is still observing GO.
        // That notification does not complete the command.  GOING first
        // clears goReg; only a later HALTED closes abstractCommandBusy.
        if (abstract_busy_ && !go_ && !abstract_started_this_edge)
          abstract_busy_ = false;
        break;
      case UINT64_C(0x104):  // GOING
        go_ = false;
        break;
      case UINT64_C(0x108):  // RESUMING
        halted_ = false;
        resume_requested_ = false;
        break;
      default:
        break;
    }
    fabric_data_ = 0;
  }

  inline static constexpr std::array<std::uint8_t, 96> kDebugRom = {
      0x6f, 0x00, 0xc0, 0x00, 0x6f, 0x00, 0x80, 0x03,
      0x6f, 0x00, 0x40, 0x04, 0x0f, 0x00, 0xf0, 0x0f,
      0x73, 0x10, 0x24, 0x7b, 0x73, 0x24, 0x40, 0xf1,
      0x23, 0x20, 0x80, 0x10, 0x03, 0x44, 0x04, 0x40,
      0x13, 0x74, 0x34, 0x00, 0xe3, 0x08, 0x04, 0xfe,
      0x13, 0x74, 0x14, 0x00, 0x63, 0x08, 0x04, 0x00,
      0x73, 0x24, 0x20, 0x7b, 0x23, 0x22, 0x00, 0x10,
      0x67, 0x00, 0x00, 0x30, 0x73, 0x24, 0x40, 0xf1,
      0x23, 0x24, 0x80, 0x10, 0x73, 0x24, 0x20, 0x7b,
      0x73, 0x00, 0x20, 0x7b, 0x23, 0x26, 0x00, 0x10,
      0x73, 0x00, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00,
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

  BoomUncachedRequest s1_{};
  BoomUncachedRequest s2_{};
  BoomUncachedRequest active_{};
  BoomUncachedCompletion lsu_response_{};
  IomshrState state_ = IomshrState::kIdle;
  std::uint8_t iomshr_state_oracle_ = 0;  // post-step face of state_
  bool entered_resp_now_ = false;
 public:
  // Debug module registers published as partition-cut lanes. The version
  // advances on every inner DMI write and abstract-command start, so the
  // publisher rewrites the 74 byte/word lanes only when one of them changed.
  const std::array<std::uint32_t, 16>& program_buffer_words() const { return program_buffer_; }
  const std::array<std::uint32_t, 2>& abstract_generated_words() const { return abstract_generated_; }
  std::uint64_t abstract_data_word() const { return abstract_data_; }
  bool go_registered() const { return go_registered_; }
  bool go_now() const { return go_; }  // goReg after this edge
  bool resume_registered() const { return resume_registered_; }
  bool resume_now() const { return resume_requested_; }
  std::uint64_t debug_register_version() const { return debug_register_version_; }
  const BoomUncachedRequest& iomshr_active_oracle() const { return active_; }
  const std::uint64_t& iomshr_grant_word_oracle() const { return grant_word_; }
  std::uint64_t iomshr_resp_data_oracle() const { return lsu_response_.data; }
  bool iomshr_entered_resp_oracle() const { return entered_resp_now_; }
  const std::uint8_t& iomshr_state_oracle() const { return iomshr_state_oracle_; }
  std::uint8_t iomshr_state_now() const {
    // RTL FSM: s_idle=0 / s_mem_access=1 / s_mem_ack=2 / s_resp=3.
    switch (state_) {
      case IomshrState::kIdle: return 0;
      case IomshrState::kMemAccess: return 1;
      case IomshrState::kWaitAck: return 2;
      case IomshrState::kResponse: return 3;
    }
    return 0;
  }
  std::uint8_t iomshr_countdown_oracle() const { return fabric_countdown_; }
 private:
  std::uint8_t fabric_countdown_ = 0;
  std::uint64_t fabric_data_ = 0;
  std::uint64_t grant_word_ = 0;
  std::uint64_t abstract_data_ = 0;
  std::uint32_t access_register_command_ = 0;
  std::array<std::uint32_t, 2> abstract_generated_{};
  std::uint8_t abstract_auto_data_ = 0;
  std::uint8_t abstract_cmderr_ = 0;
  std::array<std::uint32_t, 16> program_buffer_{};

  bool halted_ = false;
  bool resume_requested_ = false;
  bool go_ = false;
  bool go_registered_ = false;   // goReg value at cycle start (register read)
  bool resume_registered_ = false;
  std::uint64_t debug_register_version_ = 0;
  bool go_armed_ = false;
  bool abstract_busy_ = false;
  bool reject_armed_ = false;
  bool dmactive_ = false;
  std::uint8_t dmi_xbar_readys_mask_ = 3;  // dmOuter dmiXbar D arbiter, reset 0x3
  bool bypass_reg_ = true;                 // dmiBypass.bar.bypass_reg image
  bool halt_request_ = false;

 public:
  /** DMCONTROL.haltreq as currently latched.  The hart-facing debug
    * interrupt is this request while the hart is not already in debug mode;
    * the system guider synthesizes the decode-time exception from it. */
  bool halt_request() const { return halt_request_; }

  /** Exact pre-edge boundary inputs seen by dmOuter.io_innerCtrl_source on
    * the most recently committed system cycle. A generated cold RTL sidecar
    * consumes this record; it does not read any DUT state. */
  const AsyncQueueSourceInputs& inner_ctrl_source_inputs_oracle() const {
    return inner_ctrl_source_inputs_oracle_;
  }

  const DebugOuterCrossingInputs& debug_outer_crossing_inputs_oracle() const {
    return debug_outer_crossing_inputs_oracle_;
  }

  bool debug_inner_clock_edge_oracle() const {
    return debug_inner_clock_edge_oracle_;
  }

  /** D-channel data of the hand CBus manager face: a Get returns the
    * memory-map word, a Put to DATA returns the value the register held
    * before the write (the RTL register router's read mux), other Puts 0. */
  std::uint64_t debug_face_data(std::uint32_t address, bool get) const {
    if (get) return debug_memory_read64(address);
    // The router's read mux drives d.data for a Put as well.  The fabric is
    // evaluated before the Debug manager A handshake is committed, so the
    // current register still holds the pre-write value here.
    if ((address & ~UINT32_C(7)) == UINT32_C(0x380)) return abstract_data_;
    return 0;
  }

  /** The nine Debug Module oracle streams computed from this model's own
    * state: the seven asynchronous-crossing registers come straight from
    * the three depth-one queues, the abstract-command control state from
    * the busy/armed flags, and the DMI crossbar arbiter mask from the
    * register above.  Validated shadow-exact against the generated
    * dmOuter/dmInner sidecars (removed after de86af23). */
  struct DebugHandOracles {
    std::uint64_t outer_xbar_readys_mask = 0;
    std::uint64_t outer_a_source_widx_bin = 0;
    std::uint64_t outer_d_sink_valid_reg = 0;
    std::uint64_t outer_inner_ctrl_ready_reg = 0;
    std::uint64_t inner_ctrl_state = 0;
    std::uint64_t inner_ctrl_sink_valid_reg = 0;
    std::uint64_t inner_d_source_ready_reg = 0;
    std::uint64_t inner_d_source_widx_bin = 0;   // partition-cut lane
    std::uint64_t inner_a_sink_cdc_reg = 0;
    std::uint64_t inner_a_sink_valid_reg = 0;
  };
  DebugHandOracles debug_hand_oracles() const {
    DebugHandOracles o;
    o.outer_xbar_readys_mask = dmi_xbar_readys_mask_;
    o.outer_a_source_widx_bin = dmi_request_queue_.source().widx_bin() ? 1u : 0u;
    o.outer_d_sink_valid_reg = dmi_response_queue_.sink().valid_reg() ? 1u : 0u;
    o.outer_inner_ctrl_ready_reg = inner_ctrl_queue_.source().ready_reg() ? 1u : 0u;
    // Debug.scala CtrlState: Waiting(0) -> CheckGenerate(1) on a legal
    // AccessRegister COMMAND (or autoexec) while cmderr == 0; one cycle
    // later Exec(2) if the command is supported and the hart halted, else
    // back to Waiting; Exec ends when the hart's HALTED notification lands
    // with go already cleared.  In this model those are exactly busy,
    // armed and the HALTED handling in service_debug_request().
    o.inner_ctrl_state =
        !abstract_busy_ ? 0u : (go_armed_ || reject_armed_) ? 1u : 2u;
    o.inner_ctrl_sink_valid_reg = inner_ctrl_queue_.sink().valid_reg() ? 1u : 0u;
    o.inner_d_source_ready_reg = dmi_response_queue_.source().ready_reg() ? 1u : 0u;
    o.inner_d_source_widx_bin = dmi_response_queue_.source().widx_bin() ? 1u : 0u;
    o.inner_a_sink_cdc_reg =
        tl_a_crossing_bits(dmi_request_queue_.sink().crossing_reg());
    o.inner_a_sink_valid_reg = dmi_request_queue_.sink().valid_reg() ? 1u : 0u;
    return o;
  }

  /** The 55-bit TileLink A beat DMIToTL builds from a DMI request, in the
    * crossing register's bit order {opcode3, param3, size2, source1,
    * address9, mask4, data32, corrupt1}: a write is PutFullData with the
    * data, a read is Get, a NOP is a zero-data Put to HARTINFO (0x48);
    * size and mask are the constant word access. */
  static std::uint64_t tl_a_crossing_bits(std::uint64_t packed_dmi) {
    // The crossing register has no reset; the generated image starts at
    // zero and only a captured beat changes it.  A packed request of zero
    // cannot be captured (NOPs never cross, and reads/writes carry op != 0).
    if (packed_dmi == 0) return 0;
    const std::uint64_t op = (packed_dmi >> 39) & 0x3;
    const std::uint64_t addr = (packed_dmi >> 32) & 0x7f;
    const std::uint64_t data = packed_dmi & UINT64_C(0xffffffff);
    const std::uint64_t opcode = op == 2 ? 0 : (op == 1 ? 4 : 0);
    const std::uint64_t address = (op == 1 || op == 2) ? (addr << 2) : 0x48;
    const std::uint64_t put_data = op == 2 ? data : 0;
    return (opcode << 52) | (UINT64_C(2) << 47) | (address << 37) |
           (UINT64_C(0xf) << 33) | (put_data << 1);
  }

 private:
  bool ndmreset_ = false;
  bool reset_sync_2_ = false;
  bool reset_sync_1_ = false;
  bool reset_sync_0_ = false;
  bool top_ack_sync_2_ = false;
  bool top_ack_sync_1_ = false;
  bool top_ack_sync_0_ = false;
  bool outer_ack_sync_2_ = false;
  bool outer_ack_sync_1_ = false;
  bool outer_ack_sync_0_ = false;
  bool inner_clock_enabled_ = true;
  bool inner_dmactive_sync_2_ = false;
  bool inner_dmactive_sync_1_ = false;
  bool inner_dmactive_sync_0_ = false;
  AsyncQueue1 dmi_request_queue_{};
  AsyncQueue1 dmi_response_queue_{};
  AsyncQueue1 inner_ctrl_queue_{};
  bool inner_ctrl_valid_reg_ = false;
  std::uint64_t inner_ctrl_bits_reg_ = 0;
  AsyncQueueSourceInputs inner_ctrl_source_inputs_oracle_{};
  DebugOuterCrossingInputs debug_outer_crossing_inputs_oracle_{};
  bool debug_inner_clock_edge_oracle_ = true;
};

}  // namespace chisa::boom_system::components
