// Shared predictor-bank register/port schema; maintained by gen_image.py.
#pragma once
#include <cstdint>
namespace chisa::boom_model {
struct PredictorBankRegisters {
  std::uint64_t REG;  // w=64 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.REG
  std::uint64_t banked_predictors_0_components_0_columns_REG[4];  // lanes at every index; w=37 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.columns_0.REG
  std::uint64_t banked_predictors_0_components_1_s1_update_bits_ghist;  // w=64 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.s1_update__bits_ghist
  std::uint64_t banked_predictors_0_components_1_tables_0_wrbypassbank_0_0;  // w=52 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_0.wrbypass__v2_bank_0_0
  std::uint64_t banked_predictors_0_components_1_tables_1_wrbypassbank_0_0;  // w=52 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_1.wrbypass__v2_bank_0_0
  std::uint64_t banked_predictors_0_components_1_tables_2_wrbypassbank_0_0;  // w=56 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_2.wrbypass__v2_bank_0_0
  std::uint64_t banked_predictors_0_components_1_tables_3_wrbypassbank_0_0;  // w=56 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_3.wrbypass__v2_bank_0_0
  std::uint64_t banked_predictors_0_components_1_tables_4_wrbypassbank_0_0;  // w=56 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_4.wrbypass__v2_bank_0_0
  std::uint64_t banked_predictors_0_components_1_tables_5_wrbypassbank_0_0;  // w=56 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_5.wrbypass__v2_bank_0_0
  std::uint64_t banked_predictors_0_components_2_REG_2_bits;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_2_bits
  std::uint64_t banked_predictors_0_components_2_REG_14_bits;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_14_bits
  std::uint64_t banked_predictors_0_components_2_REG_26_bits;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_26_bits
  std::uint64_t banked_predictors_0_components_2_REG_38_bits;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_38_bits
  std::uint64_t banked_predictors_0_components_3_REG_2_predicted_pc_bits;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.REG_2_predicted_pc_bits
  std::uint64_t banked_predictors_0_components_3_REG_4_predicted_pc_bits;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.REG_4_predicted_pc_bits
  std::uint64_t banked_predictors_0_components_3_REG_6_predicted_pc_bits;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.REG_6_predicted_pc_bits
  std::uint64_t banked_predictors_0_components_3_REG_predicted_pc_bits;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.REG_predicted_pc_bits
  std::uint64_t banked_predictors_0_components_3_btbbank_0[16];  // lanes at every index; w=52 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.btb__v2_bank_0_0
  std::uint64_t banked_predictors_0_components_3_metabank_0_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_0_0
  std::uint64_t banked_predictors_0_components_3_metabank_1_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_1_0
  std::uint64_t banked_predictors_0_components_3_metabank_2_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_2_0
  std::uint64_t banked_predictors_0_components_3_metabank_3_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_3_0
  std::uint64_t banked_predictors_0_components_3_metabank_4_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_4_0
  std::uint64_t banked_predictors_0_components_3_metabank_5_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_5_0
  std::uint64_t banked_predictors_0_components_3_metabank_6_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_6_0
  std::uint64_t banked_predictors_0_components_3_metabank_7_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_7_0
  std::uint64_t banked_predictors_0_components_3_metabank_8_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_8_0
  std::uint64_t banked_predictors_0_components_3_metabank_9_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_9_0
  std::uint64_t banked_predictors_0_components_3_metabank_10_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_10_0
  std::uint64_t banked_predictors_0_components_3_metabank_11_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_11_0
  std::uint64_t banked_predictors_0_components_3_metabank_12_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_12_0
  std::uint64_t banked_predictors_0_components_3_metabank_16_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_16_0
  std::uint64_t banked_predictors_0_components_3_metabank_17_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_17_0
  std::uint64_t banked_predictors_0_components_3_metabank_18_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_18_0
  std::uint64_t banked_predictors_0_components_3_metabank_19_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_19_0
  std::uint64_t banked_predictors_0_components_3_metabank_20_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_20_0
  std::uint64_t banked_predictors_0_components_3_metabank_21_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_21_0
  std::uint64_t banked_predictors_0_components_3_metabank_22_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_22_0
  std::uint64_t banked_predictors_0_components_3_metabank_23_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_23_0
  std::uint64_t banked_predictors_0_components_3_metabank_24_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_24_0
  std::uint64_t banked_predictors_0_components_3_metabank_25_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_25_0
  std::uint64_t banked_predictors_0_components_3_metabank_26_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_26_0
  std::uint64_t banked_predictors_0_components_3_metabank_27_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_27_0
  std::uint64_t banked_predictors_0_components_3_metabank_28_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_28_0
  std::uint64_t banked_predictors_0_components_3_metabank_32_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_32_0
  std::uint64_t banked_predictors_0_components_3_metabank_33_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_33_0
  std::uint64_t banked_predictors_0_components_3_metabank_34_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_34_0
  std::uint64_t banked_predictors_0_components_3_metabank_35_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_35_0
  std::uint64_t banked_predictors_0_components_3_metabank_36_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_36_0
  std::uint64_t banked_predictors_0_components_3_metabank_37_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_37_0
  std::uint64_t banked_predictors_0_components_3_metabank_38_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_38_0
  std::uint64_t banked_predictors_0_components_3_metabank_39_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_39_0
  std::uint64_t banked_predictors_0_components_3_metabank_40_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_40_0
  std::uint64_t banked_predictors_0_components_3_metabank_41_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_41_0
  std::uint64_t banked_predictors_0_components_3_metabank_42_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_42_0
  std::uint64_t banked_predictors_0_components_3_metabank_43_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_43_0
  std::uint64_t banked_predictors_0_components_3_metabank_44_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_44_0
  std::uint64_t banked_predictors_0_components_3_metabank_48_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_48_0
  std::uint64_t banked_predictors_0_components_3_metabank_49_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_49_0
  std::uint64_t banked_predictors_0_components_3_metabank_50_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_50_0
  std::uint64_t banked_predictors_0_components_3_metabank_51_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_51_0
  std::uint64_t banked_predictors_0_components_3_metabank_52_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_52_0
  std::uint64_t banked_predictors_0_components_3_metabank_53_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_53_0
  std::uint64_t banked_predictors_0_components_3_metabank_54_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_54_0
  std::uint64_t banked_predictors_0_components_3_metabank_55_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_55_0
  std::uint64_t banked_predictors_0_components_3_metabank_56_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_56_0
  std::uint64_t banked_predictors_0_components_3_metabank_57_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_57_0
  std::uint64_t banked_predictors_0_components_3_metabank_58_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_58_0
  std::uint64_t banked_predictors_0_components_3_metabank_59_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_59_0
  std::uint64_t banked_predictors_0_components_3_metabank_60_0;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_60_0
  std::uint64_t banked_predictors_0_components_3_s1_pc;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.s1_pc
  std::uint64_t banked_predictors_0_components_4_wrbypassbank_0_0;  // w=38 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_4.wrbypass__v2_bank_0_0
  std::uint64_t banked_predictors_0_components_s1_idx[4];  // lanes at 0,2,3; w=37 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.s1_idx
  std::uint64_t banked_predictors_0_components_s1_update_idx[4];  // lanes at 0,3; w=37 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.s1_update_idx
  std::uint32_t banked_predictors_0_components_3_metabank_64_0;  // w=24 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.meta__v2_bank_64_0
  std::uint16_t banked_predictors_0_components_0_columns_f3_entry_p_cnt[4];  // lanes at every index; w=10 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.columns_0.f3_entry_p_cnt
  std::uint16_t banked_predictors_0_components_0_columns_f3_entry_s_cnt[4];  // lanes at every index; w=10 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.columns_0.f3_entry_s_cnt
  std::uint16_t banked_predictors_0_components_0_columns_f3_entry_tag[4];  // lanes at every index; w=10 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.columns_0.f3_entry_tag
  std::uint16_t banked_predictors_0_components_0_columns_f3_tag[4];  // lanes at every index; w=10 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.columns_0.f3_tag
  std::uint8_t banked_predictors_0_components_0_columns_f3_entry_age[4];  // lanes at every index; w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.columns_0.f3_entry_age
  std::uint8_t banked_predictors_0_components_0_columns_f3_entry_conf[4];  // lanes at every index; w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.columns_0.f3_entry_conf
  std::uint8_t banked_predictors_0_components_0_columns_reset_idx[4];  // lanes at every index; w=4 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.columns_0.reset_idx
  std::uint8_t banked_predictors_0_components_0_s1_mask;  // w=4 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.s1_mask
  std::uint8_t banked_predictors_0_components_1_prng_1_state_0;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.prng_1.state_0
  std::uint8_t banked_predictors_0_components_1_prng_2_state_0;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.prng_2.state_0
  std::uint8_t banked_predictors_0_components_1_prng_3_state_0;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.prng_3.state_0
  std::uint8_t banked_predictors_0_components_1_prng_state_0;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.prng.state_0
  std::uint8_t banked_predictors_0_components_1_tables_0_REG_1;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_0.REG_1
  std::uint8_t banked_predictors_0_components_1_tables_0_REG_2;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_0.REG_2
  std::uint8_t banked_predictors_0_components_1_tables_0_REG_3;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_0.REG_3
  std::uint8_t banked_predictors_0_components_1_tables_0_REG_4;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_0.REG_4
  std::uint8_t banked_predictors_0_components_1_tables_0_REG_5;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_0.REG_5
  std::uint8_t banked_predictors_0_components_1_tables_0_REG_6;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_0.REG_6
  std::uint8_t banked_predictors_0_components_1_tables_0_REG_7;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_0.REG_7
  std::uint8_t banked_predictors_0_components_1_tables_0_REG_8;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_0.REG_8
  std::uint8_t banked_predictors_0_components_1_tables_0_REG_9;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_0.REG_9
  std::uint8_t banked_predictors_0_components_1_tables_0_REG_10;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_0.REG_10
  std::uint8_t banked_predictors_0_components_1_tables_0_REG_11;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_0.REG_11
  std::uint8_t banked_predictors_0_components_1_tables_1_REG_1;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_1.REG_1
  std::uint8_t banked_predictors_0_components_1_tables_1_REG_2;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_1.REG_2
  std::uint8_t banked_predictors_0_components_1_tables_1_REG_3;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_1.REG_3
  std::uint8_t banked_predictors_0_components_1_tables_1_REG_4;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_1.REG_4
  std::uint8_t banked_predictors_0_components_1_tables_1_REG_5;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_1.REG_5
  std::uint8_t banked_predictors_0_components_1_tables_1_REG_6;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_1.REG_6
  std::uint8_t banked_predictors_0_components_1_tables_1_REG_7;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_1.REG_7
  std::uint8_t banked_predictors_0_components_1_tables_1_REG_8;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_1.REG_8
  std::uint8_t banked_predictors_0_components_1_tables_1_REG_9;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_1.REG_9
  std::uint8_t banked_predictors_0_components_1_tables_1_REG_10;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_1.REG_10
  std::uint8_t banked_predictors_0_components_1_tables_1_REG_11;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_1.REG_11
  std::uint8_t banked_predictors_0_components_1_tables_2_REG_1;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_2.REG_1
  std::uint8_t banked_predictors_0_components_1_tables_2_REG_2;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_2.REG_2
  std::uint8_t banked_predictors_0_components_1_tables_2_REG_3;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_2.REG_3
  std::uint8_t banked_predictors_0_components_1_tables_2_REG_4;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_2.REG_4
  std::uint8_t banked_predictors_0_components_1_tables_2_REG_5;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_2.REG_5
  std::uint8_t banked_predictors_0_components_1_tables_2_REG_6;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_2.REG_6
  std::uint8_t banked_predictors_0_components_1_tables_2_REG_7;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_2.REG_7
  std::uint8_t banked_predictors_0_components_1_tables_2_REG_8;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_2.REG_8
  std::uint8_t banked_predictors_0_components_1_tables_2_REG_9;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_2.REG_9
  std::uint8_t banked_predictors_0_components_1_tables_2_REG_10;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_2.REG_10
  std::uint8_t banked_predictors_0_components_1_tables_2_REG_11;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_2.REG_11
  std::uint8_t banked_predictors_0_components_1_tables_3_REG_1;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_3.REG_1
  std::uint8_t banked_predictors_0_components_1_tables_3_REG_2;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_3.REG_2
  std::uint8_t banked_predictors_0_components_1_tables_3_REG_3;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_3.REG_3
  std::uint8_t banked_predictors_0_components_1_tables_3_REG_4;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_3.REG_4
  std::uint8_t banked_predictors_0_components_1_tables_3_REG_5;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_3.REG_5
  std::uint8_t banked_predictors_0_components_1_tables_3_REG_6;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_3.REG_6
  std::uint8_t banked_predictors_0_components_1_tables_3_REG_7;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_3.REG_7
  std::uint8_t banked_predictors_0_components_1_tables_3_REG_8;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_3.REG_8
  std::uint8_t banked_predictors_0_components_1_tables_3_REG_9;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_3.REG_9
  std::uint8_t banked_predictors_0_components_1_tables_3_REG_10;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_3.REG_10
  std::uint8_t banked_predictors_0_components_1_tables_3_REG_11;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_3.REG_11
  std::uint8_t banked_predictors_0_components_1_tables_4_REG_1;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_4.REG_1
  std::uint8_t banked_predictors_0_components_1_tables_4_REG_2;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_4.REG_2
  std::uint8_t banked_predictors_0_components_1_tables_4_REG_3;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_4.REG_3
  std::uint8_t banked_predictors_0_components_1_tables_4_REG_4;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_4.REG_4
  std::uint8_t banked_predictors_0_components_1_tables_4_REG_5;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_4.REG_5
  std::uint8_t banked_predictors_0_components_1_tables_4_REG_6;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_4.REG_6
  std::uint8_t banked_predictors_0_components_1_tables_4_REG_7;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_4.REG_7
  std::uint8_t banked_predictors_0_components_1_tables_4_REG_8;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_4.REG_8
  std::uint8_t banked_predictors_0_components_1_tables_4_REG_9;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_4.REG_9
  std::uint8_t banked_predictors_0_components_1_tables_4_REG_10;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_4.REG_10
  std::uint8_t banked_predictors_0_components_1_tables_4_REG_11;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_4.REG_11
  std::uint8_t banked_predictors_0_components_1_tables_5_REG_1;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_5.REG_1
  std::uint8_t banked_predictors_0_components_1_tables_5_REG_2;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_5.REG_2
  std::uint8_t banked_predictors_0_components_1_tables_5_REG_3;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_5.REG_3
  std::uint8_t banked_predictors_0_components_1_tables_5_REG_4;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_5.REG_4
  std::uint8_t banked_predictors_0_components_1_tables_5_REG_5;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_5.REG_5
  std::uint8_t banked_predictors_0_components_1_tables_5_REG_6;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_5.REG_6
  std::uint8_t banked_predictors_0_components_1_tables_5_REG_7;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_5.REG_7
  std::uint8_t banked_predictors_0_components_1_tables_5_REG_8;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_5.REG_8
  std::uint8_t banked_predictors_0_components_1_tables_5_REG_9;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_5.REG_9
  std::uint8_t banked_predictors_0_components_1_tables_5_REG_10;  // w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_5.REG_10
  std::uint8_t banked_predictors_0_components_1_tables_5_REG_11;  // w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_5.REG_11
  std::uint8_t banked_predictors_0_components_1_tables_REG[6];  // lanes at every index; w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_0.REG
  std::uint8_t banked_predictors_0_components_1_tables_doing_reset[6];  // lanes at every index; w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_0.doing_reset
  std::uint8_t banked_predictors_0_components_1_tables_wrbypass_enq_idx[6];  // lanes at every index; w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_0.wrbypass_enq_idx
  std::uint8_t banked_predictors_0_components_2_REG_1;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_1
  std::uint8_t banked_predictors_0_components_2_REG_2_valid;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_2_valid
  std::uint8_t banked_predictors_0_components_2_REG_3;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_3
  std::uint8_t banked_predictors_0_components_2_REG_4;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_4
  std::uint8_t banked_predictors_0_components_2_REG_5;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_5
  std::uint8_t banked_predictors_0_components_2_REG_7;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_7
  std::uint8_t banked_predictors_0_components_2_REG_12;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_12
  std::uint8_t banked_predictors_0_components_2_REG_13;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_13
  std::uint8_t banked_predictors_0_components_2_REG_14_valid;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_14_valid
  std::uint8_t banked_predictors_0_components_2_REG_15;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_15
  std::uint8_t banked_predictors_0_components_2_REG_16;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_16
  std::uint8_t banked_predictors_0_components_2_REG_17;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_17
  std::uint8_t banked_predictors_0_components_2_REG_19;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_19
  std::uint8_t banked_predictors_0_components_2_REG_24;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_24
  std::uint8_t banked_predictors_0_components_2_REG_25;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_25
  std::uint8_t banked_predictors_0_components_2_REG_26_valid;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_26_valid
  std::uint8_t banked_predictors_0_components_2_REG_27;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_27
  std::uint8_t banked_predictors_0_components_2_REG_28;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_28
  std::uint8_t banked_predictors_0_components_2_REG_29;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_29
  std::uint8_t banked_predictors_0_components_2_REG_31;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_31
  std::uint8_t banked_predictors_0_components_2_REG_36;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_36
  std::uint8_t banked_predictors_0_components_2_REG_37;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_37
  std::uint8_t banked_predictors_0_components_2_REG_38_valid;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_38_valid
  std::uint8_t banked_predictors_0_components_2_REG_39;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_39
  std::uint8_t banked_predictors_0_components_2_REG_40;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_40
  std::uint8_t banked_predictors_0_components_2_REG_41;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_41
  std::uint8_t banked_predictors_0_components_2_REG_43;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_43
  std::uint8_t banked_predictors_0_components_2_REG_48;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.REG_48
  std::uint8_t banked_predictors_0_components_2_f3_meta_write_way;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.f3_meta_write_way
  std::uint8_t banked_predictors_0_components_2_reset_idx;  // w=7 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.reset_idx
  std::uint8_t banked_predictors_0_components_3_REG_2_predicted_pc_valid;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.REG_2_predicted_pc_valid
  std::uint8_t banked_predictors_0_components_3_REG_4_predicted_pc_valid;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.REG_4_predicted_pc_valid
  std::uint8_t banked_predictors_0_components_3_REG_6_predicted_pc_valid;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.REG_6_predicted_pc_valid
  std::uint8_t banked_predictors_0_components_3_REG_9;  // w=8 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.REG_9
  std::uint8_t banked_predictors_0_components_3_REG_predicted_pc_valid;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.REG_predicted_pc_valid
  std::uint8_t banked_predictors_0_components_3_s1_update_bits_cfi_is_jal;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_3.s1_update__bits_cfi_is_jal
  std::uint8_t banked_predictors_0_components_4_REG;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_4.REG
  std::uint8_t banked_predictors_0_components_4_REG_1;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_4.REG_1
  std::uint8_t banked_predictors_0_components_4_REG_2;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_4.REG_2
  std::uint8_t banked_predictors_0_components_4_REG_3;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_4.REG_3
  std::uint8_t banked_predictors_0_components_4_doing_reset;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_4.doing_reset
  std::uint8_t banked_predictors_0_components_4_s2_req_rdata[4];  // lanes at every index; w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_4.s2_req_rdata_0
  std::uint8_t banked_predictors_0_components_4_wrbypass_enq_idx;  // w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_4.wrbypass_enq_idx
  std::uint8_t banked_predictors_0_components_s1_update_bits_br_mask[4];  // lanes at 0,1,3; w=4 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.s1_update__bits_br_mask
  std::uint8_t banked_predictors_0_components_s1_update_bits_btb_mispredicts[4];  // lanes at 1,3; w=4 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.s1_update__bits_btb_mispredicts
  std::uint8_t banked_predictors_0_components_s1_update_bits_cfi_idx_bits[4];  // lanes at 1,3; w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.s1_update__bits_cfi_idx_bits
  std::uint8_t banked_predictors_0_components_s1_update_bits_cfi_idx_valid[4];  // lanes at 1,3; w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.s1_update__bits_cfi_idx_valid
  std::uint8_t banked_predictors_0_components_s1_update_bits_cfi_mispredicted[2];  // lanes at every index; w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.s1_update__bits_cfi_mispredicted
  std::uint8_t banked_predictors_0_components_s1_update_bits_cfi_taken[4];  // lanes at 1,3; w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.s1_update__bits_cfi_taken
  std::uint8_t banked_predictors_0_components_s1_update_bits_is_mispredict_update[4];  // lanes at 1,3; w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.s1_update__bits_is_mispredict_update
  std::uint8_t banked_predictors_0_components_s1_update_bits_is_repair_update[4];  // lanes at 0,1,3; w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.s1_update__bits_is_repair_update
  std::uint8_t banked_predictors_0_components_s1_valid[5];  // lanes at 0,3,4; w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.s1_valid
  std::uint8_t pad_[6];
};

struct PredictorBankPorts {
  std::uint64_t banked_predictors_0_components_2_ebtb_s1_req_rebtb;  // w=40 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.ebtb.s1_req_rebtb
  std::uint32_t banked_predictors_0_components_0_columns_0_state_entries_r[2];  // lanes at every index; w=23 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.columns_0.__v2_state_entries.r0
  std::uint32_t banked_predictors_0_components_0_columns_1_state_entries_r[2];  // lanes at every index; w=23 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.columns_1.__v2_state_entries.r0
  std::uint32_t banked_predictors_0_components_0_columns_2_state_entries_r[2];  // lanes at every index; w=23 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.columns_2.__v2_state_entries.r0
  std::uint32_t banked_predictors_0_components_0_columns_3_state_entries_r[2];  // lanes at every index; w=23 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.columns_3.__v2_state_entries.r0
  std::uint32_t banked_predictors_0_components_2_meta_0_0_MPORT_2;  // w=31 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.meta_0_0.MPORT_2
  std::uint32_t banked_predictors_0_components_2_meta_0_1_MPORT_2;  // w=31 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.meta_0_1.MPORT_2
  std::uint32_t banked_predictors_0_components_2_meta_0_2_MPORT_2;  // w=31 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.meta_0_2.MPORT_2
  std::uint32_t banked_predictors_0_components_2_meta_0_3_MPORT_2;  // w=31 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.meta_0_3.MPORT_2
  std::uint32_t banked_predictors_0_components_2_meta_1_0_MPORT_3;  // w=31 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.meta_1_0.MPORT_3
  std::uint32_t banked_predictors_0_components_2_meta_1_1_MPORT_3;  // w=31 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.meta_1_1.MPORT_3
  std::uint32_t banked_predictors_0_components_2_meta_1_2_MPORT_3;  // w=31 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.meta_1_2.MPORT_3
  std::uint32_t banked_predictors_0_components_2_meta_1_3_MPORT_3;  // w=31 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.meta_1_3.MPORT_3
  std::uint16_t banked_predictors_0_components_0_columns_0_state_entries_1_r[2];  // lanes at every index; w=10 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.columns_0.__v2_state_entries_1.r0
  std::uint16_t banked_predictors_0_components_0_columns_1_state_entries_1_r[2];  // lanes at every index; w=10 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.columns_1.__v2_state_entries_1.r0
  std::uint16_t banked_predictors_0_components_0_columns_2_state_entries_1_r[2];  // lanes at every index; w=10 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.columns_2.__v2_state_entries_1.r0
  std::uint16_t banked_predictors_0_components_0_columns_3_state_entries_1_r[2];  // lanes at every index; w=10 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.columns_3.__v2_state_entries_1.r0
  std::uint16_t banked_predictors_0_components_1_tables_0_table_MPORT[4];  // lanes at every index; w=11 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_0.table_0.MPORT
  std::uint16_t banked_predictors_0_components_1_tables_1_table_MPORT[4];  // lanes at every index; w=11 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_1.table_0.MPORT
  std::uint16_t banked_predictors_0_components_1_tables_2_table_MPORT[4];  // lanes at every index; w=12 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_2.table_0.MPORT
  std::uint16_t banked_predictors_0_components_1_tables_3_table_MPORT[4];  // lanes at every index; w=12 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_3.table_0.MPORT
  std::uint16_t banked_predictors_0_components_1_tables_4_table_MPORT[4];  // lanes at every index; w=13 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_4.table_0.MPORT
  std::uint16_t banked_predictors_0_components_1_tables_5_table_MPORT[4];  // lanes at every index; w=13 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_5.table_0.MPORT
  std::uint16_t banked_predictors_0_components_2_btb_0_MPORT[4];  // lanes at every index; w=14 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.btb_0_0.MPORT
  std::uint16_t banked_predictors_0_components_2_btb_1_0_MPORT_1;  // w=14 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.btb_1_0.MPORT_1
  std::uint16_t banked_predictors_0_components_2_btb_1_1_MPORT_1;  // w=14 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.btb_1_1.MPORT_1
  std::uint16_t banked_predictors_0_components_2_btb_1_2_MPORT_1;  // w=14 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.btb_1_2.MPORT_1
  std::uint16_t banked_predictors_0_components_2_btb_1_3_MPORT_1;  // w=14 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_2.btb_1_3.MPORT_1
  std::uint8_t banked_predictors_0_components_0_columns_0_state_entries_0_r[2];  // lanes at every index; w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.columns_0.__v2_state_entries_0.r0
  std::uint8_t banked_predictors_0_components_0_columns_1_state_entries_0_r[2];  // lanes at every index; w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.columns_1.__v2_state_entries_0.r0
  std::uint8_t banked_predictors_0_components_0_columns_2_state_entries_0_r[2];  // lanes at every index; w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.columns_2.__v2_state_entries_0.r0
  std::uint8_t banked_predictors_0_components_0_columns_3_state_entries_0_r[2];  // lanes at every index; w=3 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_0.columns_3.__v2_state_entries_0.r0
  std::uint8_t banked_predictors_0_components_1_tables_0_hi_us_s2_req_rhius[4];  // lanes at every index; w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_0.hi_us_0.s2_req_rhius
  std::uint8_t banked_predictors_0_components_1_tables_0_lo_us_s2_req_rlous[4];  // lanes at every index; w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_0.lo_us_0.s2_req_rlous
  std::uint8_t banked_predictors_0_components_1_tables_1_hi_us_s2_req_rhius[4];  // lanes at every index; w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_1.hi_us_0.s2_req_rhius
  std::uint8_t banked_predictors_0_components_1_tables_1_lo_us_s2_req_rlous[4];  // lanes at every index; w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_1.lo_us_0.s2_req_rlous
  std::uint8_t banked_predictors_0_components_1_tables_2_hi_us_s2_req_rhius[4];  // lanes at every index; w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_2.hi_us_0.s2_req_rhius
  std::uint8_t banked_predictors_0_components_1_tables_2_lo_us_s2_req_rlous[4];  // lanes at every index; w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_2.lo_us_0.s2_req_rlous
  std::uint8_t banked_predictors_0_components_1_tables_3_hi_us_s2_req_rhius[4];  // lanes at every index; w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_3.hi_us_0.s2_req_rhius
  std::uint8_t banked_predictors_0_components_1_tables_3_lo_us_s2_req_rlous[4];  // lanes at every index; w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_3.lo_us_0.s2_req_rlous
  std::uint8_t banked_predictors_0_components_1_tables_4_hi_us_s2_req_rhius[4];  // lanes at every index; w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_4.hi_us_0.s2_req_rhius
  std::uint8_t banked_predictors_0_components_1_tables_4_lo_us_s2_req_rlous[4];  // lanes at every index; w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_4.lo_us_0.s2_req_rlous
  std::uint8_t banked_predictors_0_components_1_tables_5_hi_us_s2_req_rhius[4];  // lanes at every index; w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_5.hi_us_0.s2_req_rhius
  std::uint8_t banked_predictors_0_components_1_tables_5_lo_us_s2_req_rlous[4];  // lanes at every index; w=1 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_1.tables_5.lo_us_0.s2_req_rlous
  std::uint8_t banked_predictors_0_components_4_data_MPORT[4];  // lanes at every index; w=2 ldut.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd.banked_predictors_0.components_4.data_0.MPORT
  std::uint8_t pad_[4];
};
}
